### ISSUE TITLE
apollo-configservice启动失败

### ISSUE THREAD

**Issue by reignsr** [ctripcorp/apollo#1054]
同一服务器上原本正常运行的configservice、adminservice、portal三个服务（0.9.1版本），shutdown.sh后，部署了0.10.2版本，configservice startup.sh启动失败，清除日志，确认进程已停止，几次尝试仍旧启动失败，原本的0.9.1版本现在也无法启动，看了日志，两个版本报错都是一样的，搞不懂真正的原因是什么，麻烦帮忙看看。
[apollo-configservice.log](https://github.com/ctripcorp/apollo/files/1901083/apollo-configservice.log)
[apollo-configservice_appapolloapollo-0.10.2apollo-configservice-8181.log](https://github.com/ctripcorp/apollo/files/1901084/apollo-configservice_appapolloapollo-0.10.2apollo-configservice-8181.log)

**Comment by nobodyiam** [comment]
看上去是有程序占着8181端口，所以tomcat起不来。

```
2018-04-11 18:20:45.172 ERROR 84766 --- [main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-8181]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8181]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:239)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:194)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:151)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.ctrip.framework.apollo.configservice.ConfigServiceApplication.main(ConfigServiceApplication.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:993)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 18 common frames omitted
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:351)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:763)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:491)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
	... 19 common frames omitted

```

**Comment by reignsr** [comment]
我也看到这个报错了，但是检索了机器，没找到占用8181的进程，先重启试试吧。

**Comment by nobodyiam** [comment]
lsof -i:8181

如果找不到进程的话，尝试用启动进程的用户执行，或者用root执行

**Comment by reignsr** [comment]
@nobodyiam 非常感谢，问题已解决，确实有个监控程序占用了端口，用sudo看到了占用的程序。
