### ISSUE TITLE
jar包运行问题

### ISSUE THREAD

**Issue by LucienMoMo** [ctripcorp/apollo#1131]
我通过maven将apollo-core,apollo-client包引入工程，在windows上的idea中正常运行，打成jar包后再linux上通过spark-submit提交，报错，spark版本为1.6.2.
报错如下：
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.smy.spark.mhf.CoreMain$.<init>(CoreMain.scala:17)
        at com.smy.spark.mhf.CoreMain$.<clinit>(CoreMain.scala)
        at com.smy.spark.mhf.CoreMain.main(CoreMain.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.internals.RemoteConfigLongPollService!
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
        at com.ctrip.framework.apollo.internals.RemoteConfigRepository.<init>(RemoteConfigRepository.java:82)
        at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createRemoteConfigRepository(DefaultConfigFactory.java:69)
        at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createLocalConfigRepository(DefaultConfigFactory.java:65)
        at com.ctrip.framework.apollo.spi.DefaultConfigFactory.create(DefaultConfigFactory.java:35)
        at com.ctrip.framework.apollo.internals.DefaultConfigManager.getConfig(DefaultConfigManager.java:37)
        at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
        at com.smy.spark.mhf.util.PropetiesUtils.getConfigService(PropetiesUtils.java:38)
        at com.smy.spark.mhf.util.PropetiesUtils.getProperty(PropetiesUtils.java:51)
        at com.smy.spark.mhf.constant.MhfConstant$.getProperty(MhfConstant.scala:49)
        at com.smy.spark.mhf.constant.MhfConstant$SPARK_PARAM$.<init>(MhfConstant.scala:23)
        at com.smy.spark.mhf.constant.MhfConstant$SPARK_PARAM$.<clinit>(MhfConstant.scala)
        ... 12 more
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.internals.RemoteConfigLongPollService!
        at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:42)
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
        ... 23 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.createStarted()Lcom/google/common/base/Stopwatch;
  at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.<init>(RemoteConfigLongPollService.java:75)
  at com.ctrip.framework.apollo.internals.DefaultInjector$ApolloModule.configure(DefaultInjector.java:62)
  while locating com.ctrip.framework.apollo.internals.RemoteConfigLongPollService

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
        ... 24 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.createStarted()Lcom/google/common/base/Stopwatch;
        at com.google.common.util.concurrent.RateLimiter$SleepingStopwatch$1.<init>(RateLimiter.java:417)
        at com.google.common.util.concurrent.RateLimiter$SleepingStopwatch.createFromSystemTimer(RateLimiter.java:416)
        at com.google.common.util.concurrent.RateLimiter.create(RateLimiter.java:130)
        at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.<init>(RemoteConfigLongPollService.java:91)
        at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService$$FastClassByGuice$$3a5b73de.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 26 more

**Comment by LucienMoMo** [comment]
@nobodyiam 已经fix了。因为guava版本过高导致，原使用的是19.0。后改为16.0.1就没有问题了

**Comment by nobodyiam** [comment]
@LucienMoMo guava 19.0我看了下是有这个方法的，你确定之前的版本是19.0？

**Comment by LucienMoMo** [comment]
@nobodyiam 
确定，是19.0.我也看到了这个方法。
不过也确实是改成16.0.1后问题解决。
因为我使用的是spark提交的任务，估计是与spark的依赖有冲突原因。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
