### ISSUE TITLE
apollo集成CAT

### ISSUE THREAD

**Issue by stoneLee81** [ctripcorp/apollo#1203]
项目里面dubbo使用SPI集成了CAT,现在打算使用apollo，配置如下：
meta-inf
  app.name=cat
  app.id=2601

meta-inf.dubbo 
  com.alibaba.dubbo.registry.RegistryFactory
    catRegistryFactoryWrapper=com.aicall.filter.dubbo.CatRegistryFactoryWrapper

  com.alibaba.dubbo.rpc.Filter
    dubboCatFilter=com.aicall.filter.dubbo.DubboCatCrossFilter
    appnameAppend=com.aicall.filter.dubbo.AppNameAppendFilter

启动报错：
2018-06-28 17:27:14 com.ctrip.framework.apollo.tracer.Tracer WARN  Tracer              .newTransaction      : 80 - Failed to create transaction for type: Apollo.MetaService, name: getConfigService
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:81) ~[apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.updateConfigServices(ConfigServiceLocator.java:102) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.tryUpdateConfigServices(ConfigServiceLocator.java:73) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.fracom.alibaba.dubbo.registry.RegistryFactorymework.apollo.internals.ConfigServiceLocator.<init>(ConfigServiceLocator.java:54) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at 
com.ctrip.framework.apollo.internals.ConfigServiceLocator$$FastClassByGuice$$2581eb37.newInstance(<generated>) [guice-3.0.jar:0.11.0-SNAPSHOT]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) [guice-3.0.jar:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60) [guice-3.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [guice-3.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) [guice-3.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.__callInContext(InjectorImpl.java:1031) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java) [guice-3.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [guice-3.0.jar:?]
	at com.google.inject.Scopes$1$1.get(Scopes.java:65) [guice-3.0.jar:?]
	at com.google.inject.SingletonScopeWrapper$ProviderWrapper.get(SingletonScopeWrapper.java:69) [SingletonScopeWrapper$ProviderWrapper.class:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.__callInContext(InjectorImpl.java:1024) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.__getInstance(InjectorImpl.java:1013) [guice-3.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java) [guice-3.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at com.google.inject.JrInjectorProxy.invoke(JrInjectorProxy.java:68) [JrInjectorProxy.class:?]
	at com.google.inject.Injector_$$_jvst9fc_0.getInstance(Injector_$$_jvst9fc_0.java) [guice-3.0.jar:?]
	at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.<init>(RemoteConfigRepository.java:81) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createRemoteConfigRepository(DefaultConfigFactory.java:69) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createLocalConfigRepository(DefaultConfigFactory.java:65) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.create(DefaultConfigFactory.java:35) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.internals.DefaultConfigManager.getConfig(DefaultConfigManager.java:37) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.initializePropertySources(PropertySourcesProcessor.java:75) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.postProcessBeanFactory(PropertySourcesProcessor.java:55) [apollo-client-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:281) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:161) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:524) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java) [spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
	at com.aicall.soa.biz.app.BootSoaBiz.main(BootSoaBiz.java:19) [classes/:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79) ~[apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	... 52 more
Caused by: java.lang.RuntimeException: Unable to get instance of MessageManager, please make sure the environment was setup correctly!
	at com.dianping.cat.Cat.setContainer(Cat.java:337) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.CatClientModule.execute(CatClientModule.java:32) ~[cat-client-2.0.0.jar:?]
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42) ~[foundation-service-4.0.0.jar:?]
	at com.dianping.cat.Cat.initialize(Cat.java:118) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.initialize(Cat.java:107) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.getProducer(Cat.java:98) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.newTransaction(Cat.java:315) ~[cat-client-2.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79) ~[apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	... 52 more
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.message.io.TransportManager
  roleHint: default
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:92) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:78) ~[foundation-service-4.0.0.jar:?]
	at com.dianping.cat.Cat.setContainer(Cat.java:334) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.CatClientModule.execute(CatClientModule.java:32) ~[cat-client-2.0.0.jar:?]
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42) ~[foundation-service-4.0.0.jar:?]
	at com.dianping.cat.Cat.initialize(Cat.java:118) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.initialize(Cat.java:107) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.getProducer(Cat.java:98) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.newTransaction(Cat.java:315) ~[cat-client-2.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79) ~[apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	... 52 more

**Comment by stoneLee81** [comment]
cat pom文件配置
<dependency>
            <groupId>com.dianping.cat</groupId>
            <artifactId>cat-core</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>
            <version>2.0.0</version>
        </dependency>

**Comment by nobodyiam** [comment]
看上去是cat初始化失败了，你确定不引入apollo的时候是不报错的？

```
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
role: com.dianping.cat.message.io.TransportManager
roleHint: default
at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:92) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) ~[foundation-service-4.0.0.jar:?]
at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:78) ~[foundation-service-4.0.0.jar:?]
at com.dianping.cat.Cat.setContainer(Cat.java:334) ~[cat-client-2.0.0.jar:?]
at com.dianping.cat.CatClientModule.execute(CatClientModule.java:32) ~[cat-client-2.0.0.jar:?]
at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10) ~[foundation-service-4.0.0.jar:?]
at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63) ~[foundation-service-4.0.0.jar:?]
at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42) ~[foundation-service-4.0.0.jar:?]
at com.dianping.cat.Cat.initialize(Cat.java:118) ~[cat-client-2.0.0.jar:?]
at com.dianping.cat.Cat.initialize(Cat.java:107) ~[cat-client-2.0.0.jar:?]
at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48) ~[cat-client-2.0.0.jar:?]
at com.dianping.cat.Cat.getProducer(Cat.java:98) ~[cat-client-2.0.0.jar:?]
at com.dianping.cat.Cat.newTransaction(Cat.java:315) ~[cat-client-2.0.0.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79) ~[apollo-core-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
... 52 more
```

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
