### ISSUE TITLE
apollo-config-server启动后报错

### ISSUE THREAD

**Issue by mwgong** [ctripcorp/apollo#1207]
java.lang.NullPointerException: null
	at com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.handleUpdatedAppNamespaces(AppNamespaceServiceWithCache.java:209)

**Comment by mwgong** [comment]
2018-06-29 14:40:33.312 ERROR 15930 --- [Apollo-AppNamespaceServiceWithCache-1] c.c.f.a.c.s.AppNamespaceServiceWithCache : Rebuild cache failed

java.lang.NullPointerException: null
	at com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.handleUpdatedAppNamespaces(AppNamespaceServiceWithCache.java:209)
	at com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.updateAndDeleteCache(AppNamespaceServiceWithCache.java:196)
	at com.ctrip.framework.apollo.configservice.service.AppNamespaceServiceWithCache.lambda$afterPropertiesSet$0(AppNamespaceServiceWithCache.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mwgong** [comment]
为什么会报rebuild cache failed
