### ISSUE TITLE
Apollo-AdminService 如何忽略非法请求 (比如head/multipart请求) 

### ISSUE THREAD

**Issue by nianjiang** [ctripcorp/apollo#1209]
生产环境, 发现如下ERROR:

```
2018-06-29 15:28:42.274 ERROR 18052 --- [nio-8090-exec-3] .c.f.a.c.c.GlobalDefaultExceptionHandler : Request method 'HEAD' not supported

org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'HEAD' not supported
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:204)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:371)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:311)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:60)
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:352)
	at org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1123)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:934)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)

```

```
2018-06-28 18:00:13.755 [http-nio-10011-exec-4] ERROR [com.ctrip.framework.apollo.common.controller.GlobalDefaultExceptionHandler]:84-Could not parse multipart servlet request; nested exceptt
ion is java.io.IOException: The temporary upload location [/tmp/tomcat.5936828426401542787.10011/work/Tomcat/localhost/ROOT] is not valid
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.5936828422
6401542787.10011/work/Tomcat/localhost/ROOT] is not valid
        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:111)
        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:85)
        at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:76)
```

后来发现使用如下命令, 可以重现ERROR:
```
curl -X HEAD "http://localhost:8090/" 
curl -F "userid=1" "http://localhost:8090/" 
```

**这种问题, 应该怎样修改来忽略非法请求?**

.

**Comment by nobodyiam** [comment]
你指的忽略是不要写错误日志？因为事实上这些请求确实是忽略了，没有被执行

如果实在要在更早之前把非法请求拦截，可以考虑加一个filter之类的，不过可能没有很大必要

**Comment by nianjiang** [comment]
谢谢回复.
是的, 不把这种错误写在ERROR中, 因为运维把所有ERROR认为严重问题, 开发会收到报警.

我看相关代码为:
com.ctrip.framework.apollo.common.controller.GlobalDefaultExceptionHandler
```
  @ExceptionHandler({HttpRequestMethodNotSupportedException.class, HttpMediaTypeException.class})
  public ResponseEntity<Map<String, Object>> badRequest(HttpServletRequest request,
                                                        ServletException ex) {
    return handleError(request, BAD_REQUEST, ex);
  }

...
  private ResponseEntity<Map<String, Object>> handleError(HttpServletRequest request,
                                                          HttpStatus status, Throwable ex) {
    String message = ex.getMessage();

    logger.error(message, ex);
    Tracer.logError(ex);
...
```

如果是"HttpRequestMethodNotSupportedException", 可以指包Warn么, 我指:
logger.warn(message, ex);

如果同意我的思路, 我可以提交代码.

**Comment by nianjiang** [comment]
Close it.
https://github.com/ctripcorp/apollo/pull/1229
