### ISSUE TITLE
系统出错，请重试或者联系系统负责人

### ISSUE THREAD

**Issue by nosixtools** [ctripcorp/apollo#1247]
一直正常运行，端口正常未被占用，重启后报这个错误，重新安装配置还是不行，下边是错误日志
```
2018-07-12 19:52:49.996 ERROR 1813 --- [Apollo-ServiceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: DEV, meta server address:

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "/services/admin": null; nested exception is org.apache.http.client.ClientProtocolException
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:123)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:103)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:33)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
	... 13 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:70)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
	... 19 common frames omitted

2018-07-12 19:52:50.915 ERROR 1813 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address:

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address:
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:172)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:90)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:47)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2018-07-12 19:52:50.915 ERROR 1813 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 35, meta server address:
```

**Comment by nosixtools** [comment]
`
curl http://localhost:8081/services/admin -v
[{"appName":"APOLLO-ADMINSERVICE","instanceId":"ip-172-31-6-56.cn-north-1.compute.internal:apollo-adminservice:8090","homepageUrl":"http://172.31.6.56:8090/"}]
`

**Comment by nosixtools** [comment]
adminservice 跑在 8090端口
configservice 跑在8081 端口
portal 跑在8070端口
eureka跑在8090端口
`eureka注册信息

Application | AMIs | Availability Zones | Status
-- | -- | -- | --
APOLLO-ADMINSERVICE | n/a (1) | (1) | UP (1) - ip-172-31-6-56.cn-north-1.compute.internal:apollo-adminservice:8090
APOLLO-CONFIGSERVICE | n/a (1) | (1) | UP (1) - ip-172-31-6-56.cn-north-1.compute.internal:apollo-configservice:8081

`

**Comment by nobodyiam** [comment]
日志中提示DEV环境的meta server address为空，build.sh里面dev_meta应该没有赋值吧。

解开apollo-portal-xx.jar，看里面的apollo-core-xx.jar中的apollo-env.properties就明白了。

**Comment by nosixtools** [comment]
这是jar报的服务里边的配置信息
local.meta=http://localhost:8080
dev.meta=
fat.meta=
uat.meta=
lpt.meta=${lpt_meta}
pro.meta=http://localhost:8081

**Comment by nosixtools** [comment]
感谢解答，问题已解决，此问题是由于 ApolloPortal.ServerConfig的 apollo.portal.envs 与工程里边的配置不一致导致的 数据库里存储的是dev 工程里开启的是prod的
