### ISSUE TITLE
整合LDAP问题

### ISSUE THREAD

**Issue by pandalin** [ctripcorp/apollo#1255]
按照：[Portal实现用户登录](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)
接入LDAP会出现多数据源问题
```java
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'apolloportaldb.server_config' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
```
application.yml
```xml
spring:
  application:
    name: apollo-portal
  profiles:
    active: github,auth
  resources:
    cache-period: 3600
  ldap:
    urls: ldap://localhost:389
    base: dc=xxx,dc=com
    username: xxx
    password: xxxx
```

**Comment by nobodyiam** [comment]
@pandalin 

你做好LDAP整合了吗？@sunguangran贡献了一个LDAP的PR #1271 看看是否可以满足你的实际使用场景？

**Comment by pandalin** [comment]
@nobodyiam 恩，已经做好了，谢谢
