### ISSUE TITLE
portal启动报错

### ISSUE THREAD

**Issue by ylpu** [ctripcorp/apollo#1281]
2018-07-23 19:45:29.729  INFO 15420 --- [erviceLocator-1] c.c.f.f.i.p.DefaultServerProvider        : Loading C:\opt\settings\server.properties
2018-07-23 19:45:29.730  INFO 15420 --- [erviceLocator-1] c.c.f.f.i.p.DefaultServerProvider        : Environment is set to [dev] by JVM system property 'env'.
2018-07-23 19:45:30.009 ERROR 15420 --- [erviceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: DEV, meta server address:http://localhost:8080

org.springframework.web.client.HttpClientErrorException: 404 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:121)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:101)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$1(AdminServiceAddressLocator.java:96)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nobodyiam** [comment]
打开 http://localhost:8080 看一下是不是正确的meta server地址，或者直接访问一下 http://localhost:8080/services/admin 看一下是否能拿到admin service的地址

**Comment by ylpu** [comment]
在PortalApplication启动时指定-Ddev_meta=http://localhost:8080是可以的，但这个是configservice的url,不是eureka的，这个让人有点困惑

**Comment by pandalin** [comment]
meta_server在config里面

**Comment by nobodyiam** [comment]
是的，eureka只是apollo config service和admin service的一个内部实现，对外界（client和portal）是不可见，具体可以参考 [Apollo配置中心设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1) 和 [Apollo配置中心架构剖析](https://mp.weixin.qq.com/s/-hUaQPzfsl9Lm3IqQW3VDQ)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
