### ISSUE TITLE
springboot2.0启动就报这个错,急,大神

### ISSUE THREAD

**Issue by showtimehzk** [ctripcorp/apollo#1324]
ERROR SpringApplication Application run failed
 com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.internals.ConfigManager!
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
	at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.initializePropertySources(PropertySourcesProcessor.java:56)
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.postProcessBeanFactory(PropertySourcesProcessor.java:39)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:282)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:162)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at com.ulie.UlieApplication.main(UlieApplication.java:30)
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to initialize Apollo Injector!
	at com.ctrip.framework.apollo.build.ApolloInjector.getInjector(ApolloInjector.java:22)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
	... 15 more
Caused by: java.util.ServiceConfigurationError: com.ctrip.framework.apollo.internals.Injector: Provider com.ctrip.framework.apollo.internals.DefaultInjector could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.ctrip.framework.foundation.internals.ServiceBootstrap.loadFirst(ServiceBootstrap.java:14)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInjector(ApolloInjector.java:20)
	... 16 more
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to initialize Guice Injector!
	at com.ctrip.framework.apollo.internals.DefaultInjector.<init>(DefaultInjector.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Module
	at com.ctrip.framework.apollo.internals.DefaultInjector.<init>(DefaultInjector.java:27)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by nobodyiam** [comment]
guice没有引入，建议通过maven形式引用apollo-client

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
