### ISSUE TITLE
spring placeholder问题

### ISSUE THREAD

**Issue by liyfgithub** [ctripcorp/apollo#1342]
已经在配置中心配置了spring.application.name参数，但是在启动的时候还是无法加载到。

在bootstrap中也配置了apollo.bootstrap.enabled = true

还是无法解决，报错如下，求各位大神科普：

`java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.application.name' in value "${spring.application.name}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:236)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:172)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:831)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	`

**Comment by liyfgithub** [comment]
@nobodyiam 是不是我什么地方配置有问题呢？

**Comment by nobodyiam** [comment]
方便上传个简单的demo吗？

**Comment by liyfgithub** [comment]
@nobodyiam 其他的配置可以，就这个不行，我用的是springclound，我的工程下面还有其他的application.yml，不是所有的配置都迁移到了apollo，只是个别；在本地的application.yml里面增加一个空值的application.name的话可以避免这个错误，但是值无法赋予上去。

**Comment by nobodyiam** [comment]
最好上传个demo吧，我本地试了一下是可以的，是不是你那里使用有啥特殊之处？

**Comment by liyfgithub** [comment]
@nobodyiam 不方便上传啊，您看下下面的报错，在springcloud启动的时候没注入进来，apollo.bootstrap.enabled = true这个配置确认是添加了。

com.netflix.discovery.DiscoveryClient    : DiscoveryClient_${SPRING.APPLICATION.NAME}/${spring.application.name}:${server.port}

**Comment by liyfgithub** [comment]
@nobodyiam 您好，我问下另外一个问题，如果工程中的配置文件和apollo配置中心有相同的key，是不是以工程中的为准？

**Comment by liyfgithub** [comment]
@nobodyiam 我这里测试了，通过placeholder获取参数值，如果工程的配置文件中存在这个key的话，配置中心就算改了这个key的value也是不会生效的，除非通过apolloConfig去拿去参数。如果工程的配置文件没有这个key的话，更改才是实时生效的。

**Comment by GINTOPN** [comment]
请问楼主是否启动了本地覆盖模式，类似这种
local-override  = true

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
