### ISSUE TITLE
[Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://169.254.176.207:8090

### ISSUE THREAD

**Issue by Marviszhao** [ctripcorp/apollo#1372]
有大神遇到这种情况吗，这个是什么情况，帮忙看下，
```
2018-08-15 15:07:35.100 ERROR 124536 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 4, meta server address: http://192.168.6.21:8080
2018-08-15 15:07:48.102  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://169.254.176.207:8090: No route to host
2018-08-15 15:07:48.102  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://169.254.176.207:8090
2018-08-15 15:07:51.103  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://169.254.176.207:8090: No route to host
2018-08-15 15:07:51.103  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://169.254.176.207:8090
2018-08-15 15:07:54.104  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://169.254.176.207:8090: No route to host
2018-08-15 15:07:54.104  INFO 124536 --- [Apollo-EnvHealthChecker-1] o.apache.http.impl.execchain.RetryExec   : Retrying request to {}->http://169.254.176.207:8090
2018-08-15 15:07:57.105 ERROR 124536 --- [Apollo-EnvHealthChecker-1] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: health, method: GET

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://169.254.176.207:8090/health": No route to host; nested exception is java.net.NoRouteToHostException: No route to host
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:190)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:95)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.NoRouteToHostException: No route to host
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
	... 15 common frames omitted

```
![image](https://user-images.githubusercontent.com/6290252/44135252-ed94d1cc-a09a-11e8-9baf-1bdfc579b305.png)

这个homepageUrl  "http://169.254.176.207:8090/" 不知道是在哪里注册的，麻烦看下是不是那个地方的缓存，谢谢！
![image](https://user-images.githubusercontent.com/6290252/44135815-33cbe494-a09d-11e8-85e8-54cd1b5c6a58.png)

**Comment by nobodyiam** [comment]
这个是admin server自动注册上来的，eureka默认会有90秒的缓存，如果你这个一直存在的话，可能就不是缓存的问题了。可以看看是不是起了多个admin service

**Comment by Marviszhao** [comment]
端口使用情况如下：
![image](https://user-images.githubusercontent.com/6290252/44184444-bcf63b80-a141-11e8-9664-25041cd81436.png)
mysql 配置如下：
![image](https://user-images.githubusercontent.com/6290252/44184472-da2b0a00-a141-11e8-965a-a5589d2024c4.png)

**Comment by Marviszhao** [comment]
![image](https://user-images.githubusercontent.com/6290252/44185172-583ce000-a145-11e8-9cc5-0481745e5b68.png)

**Comment by Marviszhao** [comment]
@nobodyiam   configservice 、adminservice 都加了如下配置还是不行
![image](https://user-images.githubusercontent.com/6290252/44186514-6c381000-a14c-11e8-8721-4ce57ae64bb9.png)

**Comment by nobodyiam** [comment]
看上去是你有另外一台机器注册到了eureka上，你连接到ApolloConfigDB看一下有多少进程连着这个库吧，比如`show processlist`

**Comment by Marviszhao** [comment]
最近又重新安装了一遍，成功了，将eureka.service.url 的地址修改为localhost，可以了
