### ISSUE TITLE
宋大神  救命啊

### ISSUE THREAD

**Issue by BillBearXiong** [ctripcorp/apollo#1423]
portal上不能创建用户 直接报500  什么情况啊  用户管理   项目权限管理   哪个文档有讲到呢？  大神  谢谢 谢谢

**Comment by nobodyiam** [comment]
报500的话，先看下portal的日志

用户管理文档在 [Portal 实现用户登录功能](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD)

项目权限管理文档在 [项目权限分配](https://github.com/ctripcorp/apollo/wiki/Apollo%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#12-%E9%A1%B9%E7%9B%AE%E6%9D%83%E9%99%90%E5%88%86%E9%85%8D)

**Comment by BillBearXiong** [comment]
哦  大神   protal报java.lang.UnsupportedOperationException: Create or update user operation is unsupported

**Comment by nobodyiam** [comment]
详细的日志信息传一下吧

**Comment by BillBearXiong** [comment]
[创建用户500.txt](https://github.com/ctripcorp/apollo/files/2338653/500.txt)
    大神  就截取这个500的异常

**Comment by oooooooz** [comment]
检查下 portal 应用的 application.yml ，active 要配为 active:  github,auth

**Comment by nobodyiam** [comment]
恩，看上去是注入的userService类型不对，应该是profile没有设置，参考一下[使用Apollo提供的Spring Security简单认证](https://github.com/ctripcorp/apollo/wiki/Portal-%E5%AE%9E%E7%8E%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E5%8A%9F%E8%83%BD#%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E4%B8%80%E4%BD%BF%E7%94%A8apollo%E6%8F%90%E4%BE%9B%E7%9A%84spring-security%E7%AE%80%E5%8D%95%E8%AE%A4%E8%AF%81)，重点看一下是否是`-Dapollo_profile=github,auth`没有设置。

```java
    if (userService instanceof SpringSecurityUserService) {
      ((SpringSecurityUserService) userService).createOrUpdate(user);
    } else {
      throw new UnsupportedOperationException("Create or update user operation is unsupported");
    }
```

**Comment by BillBearXiong** [comment]
@nobodyiam   宋大神  在protal 的application.yml配置文件加入apollo_profile=github,auth报以下错误
[继续报错.txt](https://github.com/ctripcorp/apollo/files/2344367/default.txt)

**Comment by BillBearXiong** [comment]
在vm启动的时候  添加-Dapollo_profile=github,auth了  打印这个信息
 Located meta server address http://localhost:8089,apollo_profile=github,auth for env DEV from com.ctrip.framework.apollo.core.internals.LegacyMetaServerProvider
   : Could not find available meta server for configured meta server addresses: http://localhost:8089,apollo_profile=github,auth, fallback to: http://localhost:8089

然后去创建用户的时候  还是500    异常是一样的

**Comment by BillBearXiong** [comment]
2018-09-03 15:39:10.613 ERROR 20052 --- [erviceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: DEV, meta server address:http://localhost:8089

org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:121)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:101)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:31)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
继续报这个错   然后去创建用户成功了  但是到配置界面报  系统出错 请联系项目负责人   @nobodyiam  宋大神  还有一个问题   关于apollo_profile=github,auth 不能放在application.yml配置文件的吗？  在vm配置-Dapollo_profile  后面要跟数据库连接的配置项  在application.yml配置文件里配置都没有用

**Comment by BillBearXiong** [comment]
宋大神   我把 configservice  adminservice 的vm 改为-Dapollo_profile=github    然后portal改成-Dapollo_profile=github,auth 好像是可以了   也不报错  也可以增加用户了   还是那个问题 -Dapollo_profile=github,auth  这个必须放到VM里吗   不能放到application.yml里吗

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
