### ISSUE TITLE
客户端无法实时获取最新配置

### ISSUE THREAD

**Issue by hitfire** [ctripcorp/apollo#1448]
![image](https://user-images.githubusercontent.com/22113766/45087408-4b098480-b138-11e8-9c52-ed0979d05cf8.png)

**Comment by hitfire** [comment]
我把apollo服务部署到服务器，本地客户端获取配置。
写了个循环获取配置
  
```
        Config config = ConfigService.getConfig("Java.WeChatMsg");
        for (int i = 0; i < 1000; i++) {
            System.out.println(DateUtil.now() + config.getProperty("accessTokenRedisKey", ""));

            try {
                Thread.sleep(10 * 1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
```
然后在客户端跑的时候更改配置，每次客户端都需要1-4分钟才能获取到最新配置
而之前测试的时候基本是实时获取，请问这种情况是正常的吗？因为我看到文档中写有：
![image](https://user-images.githubusercontent.com/22113766/45087658-46919b80-b139-11e8-8a7f-0647a52dc75e.png)
可是之前测试的时候是实时的，这种方式写的也是实时获取
![image](https://user-images.githubusercontent.com/22113766/45087721-6f199580-b139-11e8-9ba9-1016aed29a39.png)
烦请帮忙解答一下，感谢！

**Comment by nobodyiam** [comment]
看一下客户端日志吧，根据你描述的现象，貌似是推送没有生效，估计是有报错之类的，1-4分钟获取到配置应该是定期拉取的

**Comment by hitfire** [comment]
的确，服务器日志显示正常推送，但是客户端没有报错，无异常日志。admin和config我直接指定要注册的域名而不是IP是否会有影响呢？startup.sh启动参数中 -Deureka.instance.ip-address=apolloapi.xxx.com

**Comment by hitfire** [comment]
问题解决了，本来以为是客户端多ip的原因，在host中加了映射关系还是没用。后面看了下portal的日志，报错apollo.meta找不到：
```
2018-09-06 09:07:58.074 ERROR 14264 --- [Apollo-ServiceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: FAT, meta server address:http://apollo.meta

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://apollo.meta/services/admin": apollo.meta; nested exception is java.net.UnknownHostException: apollo.meta
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:121)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:101)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:31)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: apollo.meta
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
	... 13 common frames omitted

```
解决了这个问题后一段时间，就能实时获取配置了
但是为何portal一直有异常，在使用管理界面时却没有任何提示呢？这里是否可以改进一下？
最后感谢帮助！
