### ISSUE TITLE
kubernetes方式部署找不到meta-service的地址

### ISSUE THREAD

**Issue by echokk11** [ctripcorp/apollo#1452]
```
[root@k8s-node1 kubernetes]# kubectl get  po -n sre -o wide
NAME                                                        READY     STATUS    RESTARTS   AGE       IP            NODE       NOMINATED NODE
deployment-apollo-admin-server-dev-776c94b7c7-78f4r         1/1       Running   0          3h        172.20.3.33   10.0.0.5   <none>
deployment-apollo-admin-server-dev-776c94b7c7-jrf9q         1/1       Running   0          3h        172.20.2.24   10.0.0.6   <none>
deployment-apollo-admin-server-dev-776c94b7c7-lnjtj         1/1       Running   0          3h        172.20.0.47   10.0.0.4   <none>
deployment-apollo-admin-server-prod-6564bf5b4b-2kwq8        0/1       Running   8          31m       172.20.2.30   10.0.0.6   <none>
deployment-apollo-admin-server-prod-6564bf5b4b-lvxmp        1/1       Running   0          3h        172.20.3.37   10.0.0.5   <none>
deployment-apollo-admin-server-prod-6564bf5b4b-w5nt4        1/1       Running   0          3h        172.20.0.51   10.0.0.4   <none>
deployment-apollo-admin-server-test-alpha-6584f47f7-5jb6d   1/1       Running   0          2h        172.20.1.32   10.0.0.7   <none>
deployment-apollo-admin-server-test-alpha-6584f47f7-78rb2   1/1       Running   0          2h        172.20.0.53   10.0.0.4   <none>
deployment-apollo-admin-server-test-alpha-6584f47f7-ph8ff   1/1       Running   0          2h        172.20.3.40   10.0.0.5   <none>
deployment-apollo-admin-server-test-beta-78fb44c6c6-5h2r2   1/1       Running   0          2h        172.20.0.55   10.0.0.4   <none>
deployment-apollo-admin-server-test-beta-78fb44c6c6-dldpd   0/1       Running   34         2h        172.20.1.34   10.0.0.7   <none>
deployment-apollo-admin-server-test-beta-78fb44c6c6-klghg   1/1       Running   0          2h        172.20.2.28   10.0.0.6   <none>
deployment-apollo-portal-server-76df8dc6f9-4zhbd            0/1       Running   32         2h        172.20.1.36   10.0.0.7   <none>
deployment-apollo-portal-server-76df8dc6f9-j52px            0/1       Running   32         2h        172.20.3.42   10.0.0.5   <none>
deployment-apollo-portal-server-76df8dc6f9-q27hs            0/1       Running   32         2h        172.20.0.56   10.0.0.4   <none>
load-generator-779c5f458c-rxbxs                             1/1       Running   1          3h        172.20.3.39   10.0.0.5   <none>
statefulset-apollo-config-server-dev-0                      1/1       Running   0          3h        172.20.3.32   10.0.0.5   <none>
statefulset-apollo-config-server-dev-1                      1/1       Running   0          3h        172.20.0.52   10.0.0.4   <none>
statefulset-apollo-config-server-dev-2                      1/1       Running   0          3h        172.20.2.27   10.0.0.6   <none>
statefulset-apollo-config-server-prod-0                     1/1       Running   0          3h        172.20.3.36   10.0.0.5   <none>
statefulset-apollo-config-server-prod-1                     1/1       Running   0          3h        172.20.2.26   10.0.0.6   <none>
statefulset-apollo-config-server-prod-2                     0/1       Running   9          32m       172.20.1.37   10.0.0.7   <none>
statefulset-apollo-config-server-test-alpha-0               1/1       Running   1          2h        172.20.1.33   10.0.0.7   <none>
statefulset-apollo-config-server-test-alpha-1               1/1       Running   0          2h        172.20.0.54   10.0.0.4   <none>
statefulset-apollo-config-server-test-alpha-2               1/1       Running   0          2h        172.20.2.29   10.0.0.6   <none>
statefulset-apollo-config-server-test-beta-0                1/1       Running   0          2h        172.20.3.41   10.0.0.5   <none>
statefulset-apollo-config-server-test-beta-1                1/1       Running   0          2h        172.20.1.35   10.0.0.7   <none>
statefulset-apollo-config-server-test-beta-2                0/1       Running   33         2h        172.20.0.57   10.0.0.4   <none>
```
部署都已经成功了，但是进去查看日志文件 ，找不到相互的Eureka地址
```
2018-09-06 15:11:28.850 ERROR 32 --- [TaskBatchingWorker-target_statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev-0] c.n.e.cluster.ReplicationTaskProcessor   : Network level connection to peer statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev; retrying after delay

com.sun.jersey.api.client.ClientHandlerException: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48)
        at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
        at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116)
        at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:71)
        at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
        at com.sun.jersey.api.client.ClientResponse.hasEntity(ClientResponse.java:549)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:180)
        ... 10 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:204)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
        at org.apache.http.conn.EofS
```

在此pod里面ping也都是通的
```
~ # ping statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev
PING statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev (172.20.3.32): 56 data bytes
64 bytes from 172.20.3.32: seq=0 ttl=62 time=0.905 ms
64 bytes from 172.20.3.32: seq=1 ttl=62 time=0.608 ms
^C
--- statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.608/0.756/0.905 ms
~ # ping statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev
PING statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev (172.20.0.52): 56 data bytes
64 bytes from 172.20.0.52: seq=0 ttl=64 time=0.049 ms
64 bytes from 172.20.0.52: seq=1 ttl=64 time=0.052 ms
^C
--- statefulset-apollo-config-server-dev-1.service-apollo-meta-server-dev ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.049/0.050/0.052 ms
```

**Comment by echokk11** [comment]
@AiotCEO 能否帮个忙看看

**Comment by nobodyiam** [comment]
看上面这个报错不是说connect timeout，而是read timeout，说明连接应该是建成功的，是等待响应超时了

**Comment by vsxen** [comment]
我不知道你最后一列的`NOMINATED NODE`是从哪里来的  k8s version？网络方案？

然后 `statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev`这个Service的IP是Ping不通的，因为iptables没有做ICMP转发 

但是你可以访问statefulset-apollo-config-server-dev-0.service-apollo-meta-server-dev:8080 

解析出来的IP应该是Service的 而不是Pod IP(172.20.3.32)

**Comment by nobodyiam** [comment]
[1.4.0](https://github.com/ctripcorp/apollo/releases/tag/v1.4.0)版本修复了几个k8s部署的问题，可以再按照[apollo-on-kubernetes](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-kubernetes/README.md)说明部署一下。
