### ISSUE TITLE
分布式部署，Net客户端一直报500错误

### ISSUE THREAD

**Issue by kaobeixingfu** [ctripcorp/apollo#1609]
查看日志发现这个错误： ERROR 8232 --- [http-nio-8060-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    
: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

**Comment by nobodyiam** [comment]
把报错的URL在浏览器打开看下具体的返回信息？

再看下服务端是否还有更多报错信息？

**Comment by birdie7761** [comment]
apollo 1.1.1升级到spring 5以后有兼容问题。

## 问题
1. .net client中的`HttpUtil.cs`中在请求时添加了`req.Headers["Authorization"] = basicAuth;`
2. 在Spring Security 5.0之前，`PasswordEncoder` 的默认值为 `NoOpPasswordEncoder` 既表示为纯文本密码,在 Spring Security 5.0.x 以后去除默认值；[spring官方说明](https://docs.spring.io/spring-security/site/docs/5.0.2.RELEASE/reference/htmlsingle/#troubleshooting)
3. apollo-configservice的报错信息
```xml
2018-10-29 10:21:53.314 ERROR 12959 --- [http-nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exc
eption

java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:238)
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198)
	at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration$LazyPasswordEncoder.matches(AuthenticationConfiguration.java:289)
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:86)
```


## 解决方法
在`apollo-configservice`的`ConfigServiceAutoConfiguration`中添加
```java
@Bean
public static NoOpPasswordEncoder passwordEncoder() {
  return (NoOpPasswordEncoder) NoOpPasswordEncoder.getInstance();
}
```

**Comment by nobodyiam** [comment]
非常感谢！方便提交一个PR吗？

**Comment by nobodyiam** [comment]
可能需要一段时间，如果着急的话，可以基于master升级一下

**Comment by nobodyiam** [comment]
1.1.2版本已经release，包含了该问题修复，详见 https://github.com/ctripcorp/apollo/releases
