### ISSUE TITLE
Java Client 异常: NoClassDefFoundError: Could not initialize class com.ctrip.framework.apollo.tracer.Tracer

### ISSUE THREAD

**Issue by elvis9xu163** [ctripcorp/apollo#1653]
第一次使用Java客户端, 示例如下:
```java
public class ApolloClient1 {
	public static void main(String[] args) {
		System.setProperty("env", "dev");
		System.setProperty("app.id", "APP1");
		System.setProperty("apollo.cluster", "C1");
		Config config = ConfigService.getAppConfig();

		System.out.println(config.getProperty("hello", null));
	}
}
```
报错:
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.ctrip.framework.apollo.tracer.Tracer
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:37)
	at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.ctrip.framework.apollo.ConfigService.getAppConfig(ConfigService.java:51)
	at com.xjd.test.any.config.apollo.hello1.ApolloClient1.main(ApolloClient1.java:15)
```
该类是存在的, 我引入的POM如下:
<pre>
    
    <dependency>
      <groupId>com.ctrip.framework.apollo</groupId>
      <artifactId>apollo-client</artifactId>
      <version>1.1.2</version>
    </dependency>
</pre>
我看源码使用的是ServiceLoader, 难道我的使用姿势不对, 求指点.

**Comment by elvis9xu163** [comment]
OK, 我知道了, 我的锅, 环境有问题
