### ISSUE TITLE
storm框架下每个bolt实例化Spring应用时报错ConcurrentModificationException

### ISSUE THREAD

**Issue by dume2007** [ctripcorp/apollo#1658]
以下是启动storm框架时有多个任务线程同时运行com.xxx.trace.storm.message.spout.RabbitmqSpout报的错。每个RabbitmqSpout会去实例化springboot，然后springboot启动时调用Apollo，Apollo初始化时调用了NAMESPACE_NAMES.clear()方法，然后报java.util.ConcurrentModificationException错了。这里面有个iterator没有synchronized解决同步问题，忘能考虑解决。

```
10:39:07.511 [Thread-20-RabbitmqSpout-executor[3 3]] ERROR org.springframework.boot.SpringApplication - Application run failed
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_131]
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747) ~[?:1.8.0_131]
	at com.google.common.collect.AbstractMapBasedMultimap.clear(AbstractMapBasedMultimap.java:289) ~[guava-19.0.jar:?]
	at com.google.common.collect.LinkedHashMultimap.clear(LinkedHashMultimap.java:538) ~[guava-19.0.jar:?]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.initializePropertySources(PropertySourcesProcessor.java:83) ~[apollo-client-1.1.0.jar:1.1.0]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.postProcessBeanFactory(PropertySourcesProcessor.java:58) ~[apollo-client-1.1.0.jar:1.1.0]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.xxx.trace.storm.SpringStormApplication.run(SpringStormApplication.java:28) [classes/:?]
	at com.xxx.trace.storm.message.spout.BaseSpout.open(BaseSpout.java:24) [classes/:?]
	at com.xxx.trace.storm.message.spout.RabbitmqSpout.open(RabbitmqSpout.java:42) [classes/:?]
	at org.apache.storm.daemon.executor$fn__4962$fn__4977.invoke(executor.clj:602) [storm-core-1.1.1.jar:1.1.1]
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) [storm-core-1.1.1.jar:1.1.1]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
10:39:07.523 [Thread-20-RabbitmqSpout-executor[3 3]] ERROR org.apache.storm.util - Async loop died!
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_131]
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747) ~[?:1.8.0_131]
	at com.google.common.collect.AbstractMapBasedMultimap.clear(AbstractMapBasedMultimap.java:289) ~[guava-19.0.jar:?]
	at com.google.common.collect.LinkedHashMultimap.clear(LinkedHashMultimap.java:538) ~[guava-19.0.jar:?]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.initializePropertySources(PropertySourcesProcessor.java:83) ~[apollo-client-1.1.0.jar:1.1.0]
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.postProcessBeanFactory(PropertySourcesProcessor.java:58) ~[apollo-client-1.1.0.jar:1.1.0]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at com.xxx.trace.storm.SpringStormApplication.run(SpringStormApplication.java:28) ~[classes/:?]
	at com.xxx.trace.storm.message.spout.BaseSpout.open(BaseSpout.java:24) ~[classes/:?]
	at com.xxx.trace.storm.message.spout.RabbitmqSpout.open(RabbitmqSpout.java:42) ~[classes/:?]
	at org.apache.storm.daemon.executor$fn__4962$fn__4977.invoke(executor.clj:602) ~[storm-core-1.1.1.jar:1.1.1]
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) [storm-core-1.1.1.jar:1.1.1]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by dume2007** [comment]
已解决！

**Comment by nobodyiam** [comment]
@dume2007 是如何解决的？

**Comment by dume2007** [comment]
@nobodyiam 我在springboot的启动类入口方法加了synchronized
可参考：[https://www.cnblogs.com/gouyg/p/storm-springboot.html](https://www.cnblogs.com/gouyg/p/storm-springboot.html)

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
