### ISSUE TITLE
Storm集成apollo, 本地IDE启动没问题，提交到集群Apollo报错

### ISSUE THREAD

**Issue by dume2007** [ctripcorp/apollo#1770]
我在main方法第一行就获取Apollo配置
```
com.ctrip.framework.apollo.Config config = ConfigService.getConfig("xx-star.storm");
```
本地IDE启动一点问题都没有，然后我打包后通过命令提交到集群开始报错了
```
bin/storm jar lib/xx-storm-1.0-SNAPSHOT.jar com.xx.storm.message.MessageTopology MessageTopology
```

报错信息如下：
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.ctrip.framework.apollo.tracer.Tracer
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:37)
        at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
        at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
        at com.xx.storm.message.MessageTopology.main(MessageTopology.java:20)
```

**Comment by dume2007** [comment]
最新报错信息”

```
10:15:12.155 [main] WARN  com.ctrip.framework.apollo.core.utils.ClassLoaderUtil - Failed to locate class path, fallback to user.dir: /Users/san/IdeaProjects/apache-storm-1.1.1
java.lang.NoSuchMethodError: com.google.common.base.Platform.stringIsNullOrEmpty(Ljava/lang/String;)Z
        at com.google.common.base.Strings.isNullOrEmpty(Strings.java:67) ~[xxx-storm-1.0-SNAPSHOT.jar:?]
        at com.ctrip.framework.apollo.core.utils.ClassLoaderUtil.<clinit>(ClassLoaderUtil.java:35) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.tracer.internals.DefaultMessageProducerManager.<init>(DefaultMessageProducerManager.java:16) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_131]
        at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_131]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) [?:1.8.0_131]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) [?:1.8.0_131]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) [?:1.8.0_131]
        at com.ctrip.framework.foundation.internals.ServiceBootstrap.loadFirst(ServiceBootstrap.java:14) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.tracer.Tracer.getProducer(Tracer.java:31) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.tracer.Tracer.<clinit>(Tracer.java:23) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.internals.DefaultInjector.<init>(DefaultInjector.java:30) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_131]
        at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_131]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) [?:1.8.0_131]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) [?:1.8.0_131]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480) [?:1.8.0_131]
        at com.ctrip.framework.foundation.internals.ServiceBootstrap.loadFirst(ServiceBootstrap.java:14) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.build.ApolloInjector.getInjector(ApolloInjector.java:20) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61) [xxx-storm-1.0-SNAPSHOT.jar:2.5]
        at com.xxx.storm.message.MessageTopology.main(MessageTopology.java:20) [original-xxx-storm-1.0-SNAPSHOT.jar:?]
Exception in thread "main" com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.internals.ConfigManager!
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
        at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
        at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
        at com.xxx.storm.message.MessageTopology.main(MessageTopology.java:20)
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to initialize Apollo Injector!
        at com.ctrip.framework.apollo.build.ApolloInjector.getInjector(ApolloInjector.java:22)
        at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
        ... 3 more
Caused by: java.util.ServiceConfigurationError: com.ctrip.framework.apollo.internals.Injector: Provider com.ctrip.framework.apollo.internals.DefaultInjector could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.ctrip.framework.foundation.internals.ServiceBootstrap.loadFirst(ServiceBootstrap.java:14)
        at com.ctrip.framework.apollo.build.ApolloInjector.getInjector(ApolloInjector.java:20)
        ... 4 more
Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to initialize Guice Injector!
        at com.ctrip.framework.apollo.internals.DefaultInjector.<init>(DefaultInjector.java:29)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 8 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
        at com.google.common.cache.CacheBuilder.setKeyStrength(CacheBuilder.java:536)
        at com.google.common.cache.CacheBuilder.weakKeys(CacheBuilder.java:532)
        at com.google.inject.internal.WeakKeySet.<init>(WeakKeySet.java:56)
        at com.google.inject.internal.InheritingState.<init>(InheritingState.java:67)
        at com.google.inject.internal.InjectorShell$Builder.getState(InjectorShell.java:209)
        at com.google.inject.internal.InjectorShell$Builder.lock(InjectorShell.java:115)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.ctrip.framework.apollo.internals.DefaultInjector.<init>(DefaultInjector.java:27)
        ... 14 more
```

**Comment by dume2007** [comment]
已解决记录下

- 没把本地打包后的jar包上传到集群服务器上
- 提交到远程集群是在本地运行的，本地storm lib目录下有两个老的jar包导致冲突：guava-16.0.1.jar、google-collections-1.0.jar
- storm框架引入了springboot，使用maven-shade-plugin需要引入spring-boot-maven-plugin

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by 1798972** [comment]
> 案例先关闭了，如还有问题，可以提供更多信息，或进群交流。

JDK1.7,导入apollo-client的1.9.0版本的pom还是报错...(开始时用1.8还是好好的)
