### ISSUE TITLE
分布式部署问题

### ISSUE THREAD

**Issue by lchpersonal** [ctripcorp/apollo#1775]
我单个机器docker模拟部署，单点部署没有任何问题；分布式部署的时候发现只有9070这一个Eureka上有注册信息，9071这个Eurka上一个注册信息都没有。 apollo-configservice端口：9070，9071；apollo-adminservice端口：9080, 9081；apollo-portal：9090。修改了ApolloConfigDB.ServerConfig表中的eureka.service.url属性，改为多个地址：http://192.168.16.13:9070/eureka/,http://192.168.16.13:9071/eureka/
现在不明白源代码中bootstrap.yml中  client.serviceUrl: defaultZone: http://${eureka.instance.hostname}:9071/eureka/ 这里要修改吗？是填写两个地址吗？

不明白为什么数据库中已经有相应的配置了，配置文件中为什么还要填写？

**Comment by lchpersonal** [comment]
我又测试了一边，即使修改bootstrap.yml中的client.serviceUrl: defaultZone，把两个地址都写上同样会出我问题，9070的eureka上出现两个注册的服务：apollo-configservice:9070 和 apollo-configservice:9071；然后9071这个eureka上刚开始有一个注册服务apollo-configservice:9070，后来就变没了，再也刷不出来了。

**Comment by nobodyiam** [comment]
只用配置 `eureka.service.url` 就可以的，eureka互相会复制的，看看日志是不是连通性有问题

**Comment by lchpersonal** [comment]
> 只用配置 `eureka.service.url` 就可以的，eureka互相会复制的，看看日志是不是连通性有问题

我都检查了，网上也没看到有人这样部署，我尝试把两个服务都停止，把两个容器的启动顺序颠倒了一下，发现情况颠倒过来了，先启动的容器9071两个注册的服务都有，9070却又都变没有了。

我看了下日志，先启动的容器会报错：
DiscoveryClient_APOLLO-CONFIGSERVICE/26062ab04341:apollo-configservice:9071 - was unable to refresh its cache! status = Cannot execute request on any known server

2018-12-14 09:26:26.051  INFO 40 --- [DiscoveryClient-InstanceInfoReplicator-0] o.a.http.impl.client.DefaultHttpClient   : I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.16.13:9070: Broken pipe (Write failed)
2018-12-14 09:26:26.052  INFO 40 --- [DiscoveryClient-InstanceInfoReplicator-0] o.a.http.impl.client.DefaultHttpClient   : Retrying request to {}->http://192.168.16.13:9070
2018-12-14 09:26:26.054 ERROR 40 --- [DiscoveryClient-InstanceInfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: org.apache.http.client.ClientProtocolException
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.register(AbstractJerseyEurekaHttpClient.java:56)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)

**Comment by lchpersonal** [comment]
我发现把他们不输在不同的机器上，ip地址不同就正常了，原来是
eureka:
  instance:
    hostname: ${hostname:localhost}
一样导致的。

**Comment by nobodyiam** [comment]
放在同一台机器上应该是没问题的，很多公司都是这么干的，从日志里面看还是因为连不上导致的，是否机器内存比较小？

**Comment by lchpersonal** [comment]
公司机器内存是够用的，128G内存，1.2T的磁盘

**Comment by lchpersonal** [comment]
我回家在自己机器上测试也是不行，先启动8080的configservice，再启动8081的configservice，8080的Eureka上显示的注册信息有8080和8081,然而8081的Eureka上只显示8080，过了一会8080也消失了。
另外，不管8080和8081的Eureka界面上 DS Replicas都不显示内容。

**Comment by lchpersonal** [comment]
> 放在同一台机器上应该是没问题的，很多公司都是这么干的，从日志里面看还是因为连不上导致的，是否机器内存比较小？

希望能帮忙解决一下呀。。。 不知道什么原因。。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
