### ISSUE TITLE
开发本地启动assembly，注册了UNKNOWN服务到eureka

### ISSUE THREAD

**Issue by wendell-dev** [ctripcorp/apollo#1806]
参考wiki里Apollo开发指南中2.1方式：
https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#21-apollo-config-service%E5%92%8Capollo-admin-service
eclipse中启动后访问http://localhost:8080/， eureka中会多一个UNKNOWN服务，该服务状态监测地址与configservice一样。

部分log：
ERROR 6964 --- [main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_**UNKNOWN**/SKY-20170630VZV - was unable to refresh its cache! status = Cannot execute request on any known server

**Comment by nobodyiam** [comment]
之前也遇到过，不过无法稳定重现，应该和Eureka的注册机制有关，你可以稳定重现吗？

**Comment by wendell-dev** [comment]
> 之前也遇到过，不过无法稳定重现，应该和Eureka的注册机制有关，你可以稳定重现吗？

可以重现，几乎在admin与config注册后(服务启动成功)，等待10秒左右，unknown将也被注册上。

**Comment by mitolH** [comment]
Hello, Is this resolved? @wendell-dev

**Comment by mitolH** [comment]
I had the same problem, when I changged the eureka port, this log will show error stack like after:
```
[ERROR] 2019-03-21 17:29:44.165 [main] com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:972): DiscoveryClient_UNKNOWN/streamax-PC - was unable to refresh its cache! status = Cannot execute request on any known server
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:414) ~[eureka-client-1.9.3.jar:1.9.3]
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:269) ~[eureka-client-1.9.3.jar:1.9.3]
	at org.springframework.cloud.netflix.eureka.CloudEurekaClient.<init>(CloudEurekaClient.java:63) ~[spring-cloud-netflix-eureka-client-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:290) ~[spring-cloud-netflix-eureka-client-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$765dd36e.CGLIB$eurekaClient$0(<generated>) ~[spring-cloud-netflix-eureka-client-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$765dd36e$$FastClassBySpringCGLIB$$64aec0ae.invoke(<generated>) ~[spring-cloud-netflix-eureka-client-2.0.1.RELEASE.jar:2.0.1.RELEASE]
```

It seems like when the 

`spring-cloud-netflix-eureka-client.jar` is on the classpath, spring-boot autoconfiguration will config 

`EurekaClientAutoConfiguration.EurekaClientConfiguration.eurekaClient(ApplicationInfoManager manager, EurekaClientConfig config)`, 

and then default is `localhost:8080`

**Comment by mitolH** [comment]
Also `apollo-client` happened.

- Version: 1.3.0
- VM options: -Dapollo.meta=http://localhost:21050 -Ddev.meta=http://localhost:21050 -Denv=dev
- app.properties set app.id
- application.yml set apollo.bootstrap.namespaces、apollo.bootstrap.enabled

log shows:
```
[ERROR] 2019-03-21 19:11:37.761 [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:83): Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8761/eureka/}
```

**Comment by mitolH** [comment]
@nobodyiam help please

**Comment by nobodyiam** [comment]
@mitolH

Looks like you are talking about a difference scenario.

What @wendell-dev mentioned in this issue was something about apollo-configservice itself.

What you mentioned was some eureka application which used apollo to inject configuratons, would you please help to upload a simple demo?

**Comment by mitolH** [comment]
I'm so sorry for this issue, I had checked my develop environment carefully. I put the `apollo-all-in-one.jar` into my run time classpath (Seems like the idea cache).

Finally, I really thanks for your response and guide. @nobodyiam

**Comment by fomeiherz** [comment]
Check 8080,8070,8090 is used by another program, and kill it, and then restart, it's success.

**Comment by ls5201314** [comment]
我有相同的问题，多了过UNKNOWN服务请问解决了吗？

**Comment by ls5201314** [comment]
> 参考wiki里Apollo开发指南中2.1方式：
> https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97#21-apollo-config-service%E5%92%8Capollo-admin-service
> eclipse中启动后访问[http://localhost:8080/，](http://localhost:8080/%EF%BC%8C) eureka中会多一个UNKNOWN服务，该服务状态监测地址与configservice一样。
> 
> 部分log：
> ERROR 6964 --- [main] com.netflix.discovery.DiscoveryClient : DiscoveryClient_**UNKNOWN**/SKY-20170630VZV - was unable to refresh its cache! status = Cannot execute request on any known server

我有相同的问题，多了过UNKNOWN服务请问解决了吗？

**Comment by ls5201314** [comment]
我也有相同的问题，多了一个UNKNOWN服务，请问解决了吗？
