### ISSUE TITLE
启动portal报错，不能从meta server找到admin server,在eureka上admin server已经注册成功

### ISSUE THREAD

**Issue by lqx1** [ctripcorp/apollo#1835]
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://localhost:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:172)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:90)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2019-01-04 10:59:46.629 ERROR 11720 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 22, meta server address: http://localhost:8080
2019-01-04 10:59:56.631 ERROR 11720 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://localhost:8080

**Comment by nobodyiam** [comment]
No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://localhost:8080

提示已经很清楚了呀，打开 管理员工具 - 系统信息 页面看看，或者可以直接通过接口看看：`http://localhost:8080/services/admin`

**Comment by lqx1** [comment]
通过接口看查不到，到底是什么原因呢？麻烦大神说一下哈

**Comment by nobodyiam** [comment]
不启动portal通过接口可以查到，一启动portal就查不到？

难不成你的Portal还会把Meta server的进程干掉？

**Comment by lqx1** [comment]
是的，就是Portal把apollo-config这个进程干掉了呢！

**Comment by nobodyiam** [comment]
是不是内存不够了之类的？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by 861816288** [comment]
群号多少呀？

**Comment by nobodyiam** [comment]
@861816288 see https://www.apolloconfig.com/#/zh/README?id=support

**Comment by liutao5121** [comment]
861816288  这个是什么群？

**Comment by dmbjz** [comment]
找半天找到坑点。。。
