### ISSUE TITLE
LDAP登录问题

### ISSUE THREAD

**Issue by shuliu8** [ctripcorp/apollo#1859]
你好，连接公司已有LDAP的服务器报错如下
Caused by: java.lang.IllegalArgumentException: searchFilter must not be null.
        at org.springframework.util.Assert.notNull(Assert.java:193)
        at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.<init>(FilterBasedLdapUserSearch.java:85)
        at com.ctrip.framework.apollo.portal.spi.configuration.AuthConfiguration$SpringSecurityLDAPConfigurer.userSearch(AuthConfiguration.java:356)
        at com.ctrip.framework.apollo.portal.spi.configuration.AuthConfiguration$SpringSecurityLDAPConfigurer$$EnhancerBySpringCGLIB$$4bf02d0d.CGLIB$userSearch$1(<generated>)
        at com.ctrip.framework.apollo.portal.spi.configuration.AuthConfiguration$SpringSecurityLDAPConfigurer$$EnhancerBySpringCGLIB$$4bf02d0d$$FastClassBySpringCGLIB$$34d542a1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
        at com.ctrip.framework.apollo.portal.spi.configuration.AuthConfiguration$SpringSecurityLDAPConfigurer$$EnhancerBySpringCGLIB$$4bf02d0d.userSearch(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 82 common frames omitted

searchFilter: "(uid={0})  这个不是固定写法吗，还是说{}里的东西是要替换掉的，替换的话 替换的配置是从哪里读的
参考过 Portal-实现用户登录功能,我的配置截图
![qq 20190111170749](https://user-images.githubusercontent.com/15522431/51024178-bf12d800-15c3-11e9-8aab-c39f7776f6d3.png)
![qq 20190111170945](https://user-images.githubusercontent.com/15522431/51024191-c4702280-15c3-11e9-8691-6d37e54dfa52.png)

**Comment by shuliu8** [comment]
不好意思  copy的时候没注意，确实是少了个s， 加上就能正常启动了

**Comment by shuliu8** [comment]
你好，我用LDAPadmin工具连得时候是能正常连接到公司LDAP服务器，但是在Portal里面配置之后一直提示LDAP健康检查不通过，报错LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1  公司域账号格式 domain/username

**Comment by nobodyiam** [comment]
只有super admin需要在系统参数中配置一下，对于ldap本身没有什么需要做的特殊设置

如果报错的话，应该还是配置的账号验证不过，建议跟一下代码debug一下看看

**Comment by shuliu8** [comment]
感谢，问题已解决能正常使用LDAP登录了，原来对active directory和openladp理解还不够；公司用的是active directory;
不过还是有些疑问：
    
![qq 2019](https://user-images.githubusercontent.com/15522431/51597322-e9ef1b80-1f35-11e9-841c-5ecc0afb9e6e.png)  红框里的几个值好像并没有起到什么作用啊，我随便写一个运行还是一样的结果；

**Comment by nobodyiam** [comment]
红框里面的是用来做搜索用户以及做用户属性映射的，随便改的话，应该在搜索用户的时候有问题的。

至于配置的username，这个要看具体设置的吧，我本地跑得是open ldap，user name就是这个样子的

@codepiano 也欢迎帮忙补充一下~

**Comment by codepiano** [comment]
> 红框里面的是用来做搜索用户以及做用户属性映射的，随便改的话，应该在搜索用户的时候有问题的。
> 
> 至于配置的username，这个要看具体设置的吧，我本地跑得是open ldap，user name就是这个样子的
> 
> @codepiano 也欢迎帮忙补充一下~

基本是这样的，ldap主要是给搜索和获取用户信息用

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
