### ISSUE TITLE
portal可以水平扩展部署多个吗？部署两个portal实例登录报错，部署一个没有问题。

### ISSUE THREAD

**Issue by xiaochiouyu** [ctripcorp/apollo#1868]
ERROR 38 --- [http-nio-8646-exec-7] .c.f.a.c.c.GlobalDefaultExceptionHandler : user id and app id can't be empty at the same time

com.ctrip.framework.apollo.common.exception.BadRequestException: user id and app id can't be empty at the same time
    at com.ctrip.framework.apollo.portal.service.FavoriteService.search(FavoriteService.java:61)
    at com.ctrip.framework.apollo.portal.controller.FavoriteController.findFavorites(FavoriteController.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)

**Comment by nobodyiam** [comment]
默认的spring security登录配置是不支持集群登录的，如果是接入的自己公司的ldap或sso应该是没问题的

**Comment by xiaochiouyu** [comment]
Thankyou~,还有一个问题，接入ldap的话，管理员这个角色怎么设置啊？例如auth的情况下的apollo

**Comment by xiaochiouyu** [comment]
已经通过直接修改数据库增加管理员。是不是只能通过修改数据库或者管理员修改系统参数来增加管理员？

**Comment by xiaochiouyu** [comment]
已经通过apollo用户修改系统参数增加管理员。是不是只能通过修改数据库或者管理员修改系统参数来增加管理员？

**Comment by nobodyiam** [comment]
是的

**Comment by xiaochiouyu** [comment]
> 默认的spring security登录配置是不支持集群登录的，如果是接入的自己公司的ldap或sso应该是没问题的

thank you，and 针对这条的话，是不是接入 open ldap，也是不支持水平扩展呢？测试接入open ldap，水平扩展两台，还是无法登录。

**Comment by nobodyiam** [comment]
默认的open ldap实现目前也是基于spring security的，所以目前也不支持集群登录，这块后续还是希望有对spring security研究比较深入的同学能贡献一点力量

**Comment by xiaochiouyu** [comment]
好的，谢谢！

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by huzhou520** [comment]
请问k8s下搭建portal怎么对接ldap，有相关文档嘛，我看ldap文档都是虚拟机上对接的文档

**Comment by nobodyiam** [comment]
对接ldap和k8s貌似没啥关系吧？
