### ISSUE TITLE
项目整合报空指针nullpointerexception PropertySourcesProcessor.java:63

### ISSUE THREAD

**Issue by xiguizi** [ctripcorp/apollo#1886]
查看发现env为空，不知道是什么原因，
java.lang.NullPointerException
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.initializePropertySources(PropertySourcesProcessor.java:63)
	at com.ctrip.framework.apollo.spring.config.PropertySourcesProcessor.postProcessBeanFactory(PropertySourcesProcessor.java:58)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:553)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:527)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:362)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)

**Comment by nobodyiam** [comment]
能麻烦上传一个demo吗？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
