### ISSUE TITLE
1.2.0版本configserver docker启动报错 EnableGlobalMethodSecurity is required

### ISSUE THREAD

**Issue by daiing** [ctripcorp/apollo#1939]
1.2.0版本github下载版本，使用官网上的dockerfile编译启动容器
portal和admin服务都启动成功，但是configserver启动失败，

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.AutoConfigurationPackages': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannotresolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'methodSecurityMetadataSource' defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.access.method.MethodSecurityMetadataSource]: Factory method 'methodSecurityMetadataSource' threw exception; nested exception is java.lang.IllegalArgumentException: org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity is required
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:490)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
        at org.springframework.boot.autoconfigure.AutoConfigurationPackages.get(AutoConfigurationPackages.java:73)
        at org.springframework.boot.autoconfigure.AutoConfigurationPackages.has(AutoConfigurationPackages.java:62)
        at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.getPackagesToScan(JpaBaseConfiguration.java:163)
        at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.entityManagerFactory(JpaBaseConfiguration.java:138)
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$ff0fcf6b.CGLIB$entityManagerFactory$5(<generated>)
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$ff0fcf6b$$FastClassBySpringCGLIB$$4d871434.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
        at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$ff0fcf6b.entityManagerFactory(<generated>)
        at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 50 common frames omitted

**Comment by nobodyiam** [comment]
修改过配置或代码吗？建议把完整的日志传上来看看

**Comment by daiing** [comment]
官方的zip和dockerfile，就改了数据库配置，启动端口，以及portal的apollo-env.properties，因为只是测试，所以删掉了其他行，就留了local.meta和dev.meta，内容如下，其中10.108.0.202:10022就是config server的地址

local.meta=http://10.108.0.202:10022
dev.meta=http://10.108.0.202:10022

**Comment by nobodyiam** [comment]
把完整的日志作为附件传上来吧

**Comment by daiing** [comment]
解决了，是因为端口冲突了，查了两天是这个原因，泪奔

**Comment by cysjtu** [comment]
这个报错太傻比了

**Comment by cysjtu** [comment]
我也找了半天

**Comment by handq** [comment]
我只启动configServer也是这个报错,哪两个端口冲突?麻烦指点下

**Comment by nobodyiam** [comment]
@handq 报这个错未必是端口冲突，从启动日志往下看第一个报错就能知道具体报错原因

**Comment by mingcanchen** [comment]
我这边也是报这个错误,我修改了端口还是一样的,有人知道怎么解决吗?

**Comment by gihubcloner** [comment]
日志挺完善的（端口冲突的场景下）

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.
