### ISSUE TITLE
BUG: apollo-1.3.0 docker部署一段时间发现configservice无法与外部通信，mysql库被清空

### ISSUE THREAD

**Issue by structure-charger** [ctripcorp/apollo#2028]
环境:测试与开发环境,系统,ubuntu 1604,docker版本17.06
部署方式:容器化部署两套环境,使用3台机器，ip尾缀分别为59,14,62,
59上部署apollo-config\admin\portal,数据库放在14上,使用宿主机ip替代容器ip注册到config-eureka上,修正配置如下: 官方release包apollo-*-1.3.0-github.zip中的config/application-github.properties，scripts/startup.sh
其中application-github.properties修改如下：
# DataSource
spring.datasource.url = jdbc:mysql://数据库ip(14):3306/ApolloConfigDB?characterEncoding=utf8

startup.sh修改如下:
**SERVER_PORT=8010**

## Adjust memory settings if necessary
#export JAVA_OPTS="-Xms2560m -Xmx2560m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:NewSize=1536m -XX:MaxNewSize=1536m -XX:SurvivorRatio=8"

## Only uncomment the following when you are using server jvm
#export JAVA_OPTS="$JAVA_OPTS -server -XX:-ReduceInitialCardMarks"

########### The following is the same for configservice, adminservice, portal ###########
export JAVA_OPTS="$JAVA_OPTS -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+ScavengeBeforeFullGC -XX:+UseCMSCompactAtFullCollection -XX:+CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSPermGenSweepingEnabled -XX:CMSInitiatingPermOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrent -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationConcurrentTime -XX:+PrintHeapAtGC -XX:+UseGCLogFileRotation -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom"
export JAVA_OPTS="$JAVA_OPTS -Dserver.port=$SERVER_PORT **-Deureka.instance.ip-address=ip(59) -Deureka.instance.homePageUrl=http://ip(59):8010** -Dlogging.file=$LOG_DIR/$SERVICE_NAME.log -Xloggc:$LOG_DIR/gc.log -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=5M -XX:HeapDumpPath=$LOG_DIR/HeapDumpOnOutOfMemoryError/"

PATH_TO_JAR=$SERVICE_NAME".jar"
**SERVER_URL="http://ip(59):$SERVER_PORT"**

admin与portal的配置与上面基本相同，只是端口做了变更。

62上的部署于59略有不同，数据库与apollo-config,apollo-admin部署在同一台机器上，不带portal,配置基本与59一致,62作为一个新的集群注册到了59的portal上，在portal上分别发布了测试与开发的应用10多个(新代码分支)，全是spring cloud应用
运行5-6天后,59服务出现异常，configservice报错如下：
2019-03-07 09:22:02.080  WARN 37 --- [main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.ConnectException: Connection refused (Connection refused)
2019-03-07 09:22:02.081 ERROR 37 --- [main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_APOLLO-CONFIGSERVICE/ee43ea3bb79b:apollo-configservice:8011 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
        at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051)
        at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965)
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:414)
        at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:269)
        at org.springframework.cloud.netflix.eureka.CloudEurekaClient.<init>(CloudEurekaClient.java:63)
        at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.eurekaClient(EurekaClientAutoConfiguration.java:290)
        at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$4a0eb0e7.CGLIB$eurekaClient$2(<generated>)
        at org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration$$EnhancerBySpringCGLIB$$4a0eb0e7$$FastClassBySpringCGLIB$$73c1be4.invoke(<generated>)

报错重复无数次，重构容器多次还是如此，因此不全部截取
caused by为connection refused
同时出现一个更严重的情况，14上的mysql数据库被全部清空，库与表结构还在，数据不翼而飞，62上没有出现这个问题。
数据库相关的日志没有找到，只发现来自59的session被abort了,原因不明，数据库连接数默认100，根本没超过最大连接数。
还未抓包或者做端口扫描，还请各路大神提供策略，代码已紧急回滚

**Comment by nobodyiam** [comment]
apollo代码中没有这类删除数据的逻辑，界面上的删除功能也都是软删，不会导致数据库被清空的，建议从数据库日志中找线索吧。

至于eureka connection refused的问题，这个就是读取的serverconfig中的eureka.service.url配置做eureka信息同步的，可以看一下配置是否正确，以及是否能访问通

**Comment by furenle** [comment]
从单机（59）到引入新集群（62）之后3天都是正常的，但是第三天config,admin突然就无法通信了eureka注册也不成功，请问跟数据库内容有关吗？

**Comment by furenle** [comment]
鉴于官方提供的jar包部署之后除了我提交的这部分日志之外没有输出其他日志，还请官方同学提供其他排查方式与思路，数据库日志只有链接断开的信息

**Comment by nobodyiam** [comment]
eureka的配置是从数据库中获取的，如果数据被清空了，那应该会向`http://localhost:8080/eureka`注册

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
