### ISSUE TITLE
ConfigService.getConfig报错

### ISSUE THREAD

**Issue by colinWaq** [ctripcorp/apollo#2117]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Lists.newCopyOnWriteArrayList()Ljava/util/concurrent/CopyOnWriteArrayList;
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.<init>(AbstractConfigRepository.java:18)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.<init>(RemoteConfigRepository.java:78)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createRemoteConfigRepository(DefaultConfigFactory.java:69)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createLocalConfigRepository(DefaultConfigFactory.java:65)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.create(DefaultConfigFactory.java:34)
	at com.ctrip.framework.apollo.internals.DefaultConfigManager.getConfig(DefaultConfigManager.java:37)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.gage.hadoopgageservicecore.main.BaseMain.start(BaseMain.java:140)
	at com.gage.python.Main.main(Main.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:153)

**Comment by colinWaq** [comment]
我看了下引入的guava版本是2.0 里面也确实存在这个方法

![image](https://user-images.githubusercontent.com/29651602/55768544-e3d9f700-5aaf-11e9-8e5d-cd5c4770ed2f.png)

**Comment by colinWaq** [comment]
运行环境是在hadoop执行的，命令是 hadoop jar XXX.jar  里面只有一个main方法  就是获取配置ConfigService.getConfig

**Comment by 13827475135** [comment]
Apollo客户端默认会引用Guava 19，如果你的项目引用了其它版本，请确保版本号大于等于15.0，你的怎么是2.0

**Comment by colinWaq** [comment]
> Apollo客户端默认会引用Guava 19，如果你的项目引用了其它版本，请确保版本号大于等于15.0，你的怎么是2.0

不好意思打错了，是20。问题调查出来了，是hadoop默认集群当中的版本是11  导致的

**Comment by colinWaq** [comment]
解决方案如下：
1 通过查看hadoop-env.sh 文件可以看到
for f in $HADOOP_HOME/contrib/capacity-scheduler/*.jar; do
  if [ "$HADOOP_CLASSPATH" ]; then
    export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$f
  else
    export HADOOP_CLASSPATH=$f
  fi
done
2 在HADOOP_HOME下创建contrib/capacity-scheduler/文件夹，并把guava-16.0.jar 放到该目录下 解决
