### ISSUE TITLE
apollo-portal 出错

### ISSUE THREAD

**Issue by fendoudexiaocainiao** [ctripcorp/apollo#2166]
现在利用docker-compose启动apollo-portal有报错,报错信息如下:
```java
2019-04-25 19:31:07.438  WARN 19 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.ConnectException: Connection refused (Connection refused)
2019-04-25 19:31:07.439  WARN 19 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/apollo-portal:8070 - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829)
        at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2019-04-25 19:31:07.439  WARN 19 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829)
        at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
我是用的`apollo-all-in-one.jar`,但是`server`和`portal`不在一个容器内.是需要修改哪一项配置吗?

**Comment by fendoudexiaocainiao** [comment]
- 以下是server的Docker构建文件:
- Dockerfile
```Dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/wanghao0921/oracle-jdk:8u192
MAINTAINER wanghao<wh564546239@gmail.com>

RUN apk add --no-cache bash && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&  \
    echo "Asia/Shanghai" > /etc/timezone && \
    mkdir /apollo-service /apollo-service/logs && \
    touch /apollo-service/logs/apollo-service.log

COPY start.sh /apollo-service
COPY apollo-all-in-one.jar /apollo-service
COPY apollo-service.conf /apollo-service

RUN chmod -R 777 /apollo-service

ENV APOLLO_CONFIG_DB_URL=jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8
ENV APOLLO_CONFIG_DB_USERNAME=root
ENV APOLLO_CONFIG_DB_PASSWORD=123456

EXPOSE 8080 8090

WORKDIR /apollo-service

CMD [ "./start.sh", "start" ]
```
- start.sh
```bash
#!/bin/bash

eureka_service_url=http://127.0.0.1:8080/eureka

base_java_opts="-Denv=dev"
server_java_opts="$base_java_opts -Dspring.profiles.active=github -Deureka.service.url=$eureka_service_url"

service_jar=./apollo-all-in-one.jar
service_log=./logs/apollo-service.log

if [ "$1" = "start" ] ; then
  echo "==== starting service ===="
  echo "Service logging file is $service_log"
  export JAVA_OPTS="$server_java_opts -Dlogging.file=$service_log -Dspring.datasource.url=$APOLLO_CONFIG_DB_URL -Dspring.datasource.username=$APOLLO_CONFIG_DB_USERNAME -Dspring.datasource.password=$APOLLO_CONFIG_DB_PASSWORD"
  $service_jar start --configservice --adminservice

  rc=$?
  if [[ $rc != 0 ]];
  then
    echo "Failed to start service, return code: $rc. Please check $service_log for more information."
    exit $rc;
  fi

  printf "Waiting for config service startup"

  rc=$?
  if [[ $rc != 0 ]];
  then
    printf "\nConfig service failed to start in $rc seconds! Please check $service_log for more information.\n"
    exit 1;
  fi

  printf "\nConfig service started. You may visit for service status now!\n"

  printf "Waiting for admin service startup"

  rc=$?
  if [[ $rc != 0 ]];
  then
    printf "\nAdmin service failed to start in $rc seconds! Please check $service_log for more information.\n"
    exit 1;
  fi

  printf "\nAdmin service started\n"
  tail -f $service_log
elif [ "$1" = "stop" ] ; then
  echo "==== stopping service ===="
  $service_jar stop
else
  echo "Usage: demo.sh ( commands ... )"
  echo "commands:"
  echo "  start         start services"
  echo "  stop          stop services"
  exit 1
fi
```
- apollo-service.conf文件没有修改我就不贴了.

- 以下是portal的Docker构建文件:
- Dockerfile
```Dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/wanghao0921/oracle-jdk:8u192
MAINTAINER wanghao<wh564546239@gmail.com>

RUN apk add --no-cache bash && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&  \
    echo "Asia/Shanghai" > /etc/timezone && \
    mkdir /apollo-portal /apollo-portal/logs && \
    touch /apollo-portal/logs/apollo-portal.log

COPY start.sh /apollo-portal
COPY apollo-all-in-one.jar /apollo-portal
COPY apollo-portal.conf /apollo-portal

RUN chmod -R 777 /apollo-portal

ENV APOLLO_PORTAL_DB_URL=jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8
ENV APOLLO_PORTAL_DB_USERNAME=root
ENV APOLLO_PORTAL_DB_PASSWORD=123456
ENV CONFIG_SERVER_URL=http://apollo-service:8080

EXPOSE 8070

WORKDIR /apollo-portal

CMD [ "./start.sh", "start" ]
```
- start.sh
```bash
#!/bin/bash

base_java_opts="-Denv=dev"
portal_java_opts="$base_java_opts -Ddev_meta=$CONFIG_SERVER_URL -Dspring.profiles.active=github,auth"

portal_jar=./apollo-all-in-one.jar
portal_log=./logs/apollo-portal.log

if [ "$1" = "start" ] ; then
  echo "==== starting portal ===="
  echo "Portal logging file is $portal_log"
  export JAVA_OPTS="$portal_java_opts -Dlogging.file=$portal_log -Dserver.port=8070 -Dspring.datasource.url=$APOLLO_PORTAL_DB_URL -Dspring.datasource.username=$APOLLO_PORTAL_DB_USERNAME -Dspring.datasource.password=$APOLLO_PORTAL_DB_PASSWORD"
  $portal_jar start --portal

  rc=$?
  if [[ $rc != 0 ]];
  then
    echo "Failed to start portal, return code: $rc. Please check $portal_log for more information."
    exit $rc;
  fi

  printf "Waiting for portal startup"

  rc=$?
  if [[ $rc != 0 ]];
  then
    printf "\nPortal failed to start in $rc seconds! Please check $portal_log for more information.\n"
    exit 1;
  fi

  printf "\nPortal started!"

  tail -f $portal_log
elif [ "$1" = "stop" ] ; then
  echo "==== stopping service ===="
  $portal_jar stop
else
  echo "Usage: demo.sh ( commands ... )"
  echo "commands:"
  echo "  start         start portal"
  echo "  stop          stop portal"
  exit 1
fi
```
- apollo-portal.conf文件没有修改我就不贴了.

**Comment by nobodyiam** [comment]
确定这个错误是apollo-portal？apollo-portal不会启用eureka的

**Comment by fendoudexiaocainiao** [comment]
> 确定这个错误是apollo-portal？apollo-portal不会启用eureka的

这个我还是能确定的,我已经把我的相关的一些配置文件贴上来了,您这边看看是不是可以重现一下,我是用的all-in-one包.

**Comment by fendoudexiaocainiao** [comment]
- 补充一下`docker-compose`的文件吧.
```yaml
version: '3'
services:
  mysql:
    image: mysql:5
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "1"
    volumes:
      - E:/DockerConfig/Mysql:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:5.0.3
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - E:/DockerConfig/Redis/config/redis.conf:/config/redis.conf
      - E:/DockerConfig/Redis/data:/data
    networks: 
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "1"
    restart: unless-stopped
    command: redis-server /config/redis.conf

  apollo-service:
    image: registry.cn-hangzhou.aliyuncs.com/wanghao0921/apollo-service:1.4.0
    container_name: apollo-service
    hostname: apollo-service
    ports:
      - 18080:8080
      - 18090:8090
    depends_on: 
      - mysql
    environment:
      - TZ=Asia/Shanghai
    networks: 
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "1"
    restart: unless-stopped
    
  apollo-portal:
    image: registry.cn-hangzhou.aliyuncs.com/wanghao0921/apollo-portal:1.4.0
    container_name: apollo-portal
    hostname: apollo-portal
    ports:
      - 18070:8070
    depends_on:
      - apollo-service
      - mysql
    environment:
      - TZ=Asia/Shanghai
    networks: 
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "1"
    restart: unless-stopped
networks: 
  default:
    external:
      name: my-net
```

**Comment by LuoLee** [comment]
遇到同样的问题，是基于 Github 上的最新代码打包的，并且运行在真实操作系统上非Docker环境
```
2019-04-29 05:33:02.628  WARN 7335 --- [DiscoveryClient-HeartbeatExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: null
2019-04-29 05:33:02.628 ERROR 7335 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/ser:8070 - was unable to send heartbeat!

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1399)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-04-29 05:33:02.656  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-04-29 05:33:02.662  WARN 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure with status code 404; retrying on another server if available
2019-04-29 05:33:02.663 ERROR 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/ser:8070 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1473)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1440)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-04-29 05:33:07.066  INFO 7335 --- [AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-04-29 05:33:07.346  INFO 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-04-29 05:33:07.351  WARN 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failure with status code 404; retrying on another server if available
2019-04-29 05:33:07.352 ERROR 7335 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/ser:8070 - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1051)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:965)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1473)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1440)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-04-29 05:33:07.379 ERROR 7335 --- [DiscoveryClient-HeartbeatExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error
```

**Comment by nobodyiam** [comment]
@fendoudexiaocainiao 

我本地跑了一下[Apollo Docker Quick Start](https://github.com/ctripcorp/apollo/wiki/Apollo-Quick-Start-Docker%E9%83%A8%E7%BD%B2)，从portal日志中确实能看到有eureka的日志，应该是由于apollo-quick-start中包含了eureka的jar包，触发了`org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration`，不过我本地跑没有报错，原因是Apollo Docker Quick Start默认是portal和service跑在一个容器中的，然后eureka的地址默认配置为localhost:8080/eureka，所以确实是能连上的。

知道了问题所在，解决办法就清楚了，启动apollo-portal时设置`-Deureka.client.enabled=false`即可，可以参考一下这个[commit](https://github.com/nobodyiam/apollo-build-scripts/commit/c61f79bd0a31e1881a78460a607c37192ead6c9d#diff-1621e745861a1671931d71ff5a5a3d75)

**Comment by nobodyiam** [comment]
apollo-quick-start已经更新，默认会为portal关闭eureka-client
