### ISSUE TITLE
docker_compose.yml 中配置没生效

### ISSUE THREAD

**Issue by wx8217** [ctripcorp/apollo#2195]
我源码编译(编译时对build.sh脚本不做任何修改)后，分别将
/apollo/apollo-protal/target、
/apollo/apollo-adminservice/target、
/apollo/apollo-configservice/target、下的*-github.zip 拷贝到对应的src/main/docker 目录下，执行docker build 分别生成三个镜像

在docker-compose.yml中配置启动的环境，如下：
apollo-portal: 
    image: apollo/apollo-protal:1.4.0
    environment: 
      DEV_META_SERVICE_NAME: apollo-configservice
      DATASOURCES_URL: jdbc:mysql://mysql:13306/ApolloPortalDB?characterEncoding=utf8
      DATASOURCES_USERNAME: root
      DATASOURCES_PASSWORD: 123456
    ports:
      - 8070:8070
    depends_on:
      - apollo-configservice
      - apollo-adminservice

启动失败，查看日志
Caused by: java.net.UnknownHostException: fill-in-the-correct-server: Name does not resolve
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
        ... 150 common frames omitted

感觉这个配置没有生效，是不是这个配置不能在这里配置？

**Comment by wx8217** [comment]
我在startup.sh 中加上export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.url=,-Dspring.datasource.username=,-Dspring.datasource.password=,-Dspring.dev.meta=
后再编译打包。
docker-compose.yml中
 environment: 
      DEV_META: apollo-configservice
      DATASOURCE_URL:jdbc:mysql://mysql:13306/ApolloPortalDB?characterEncoding=utf8
      DATASOURCE_USERNAME:root
      DATASOURCE_PASSWORD:123456

启动
2019-05-06 18:10:44.610 ERROR 37 --- [localhost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creati
ng bean with name 'openApiAuthenticationFilter' defined in class path resource [com/ctrip/framework/apollo/portal/spi/configuration/AuthFilterConfiguration.class]: Unsatisfied dependency expressed through method 'openApiAuthenticatio
nFilter' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consumerAuthUtil' defined in URL [jar:file:/apollo-portal/apollo-portal.jar!/com/ctrip/framewo
rk/apollo/openapi/util/ConsumerAuthUtil.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'co
nsumerService' defined in URL [jar:file:/apollo-portal/apollo-portal.jar!/com/ctrip/framework/apollo/openapi/service/ConsumerService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.sp
ringframework.beans.factory.BeanCreationException: Error creating bean with name 'consumerTokenRepository': Cannot create inner bean '(inner bean)#63967835' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setti
ng bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#63967835': Cannot resolve reference to bean 'entityManagerFactory' while setti
ng constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied depe
ndency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoco
nfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: F
actory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: URL must start with 'jdbc'
2019-05-06 18:10:44.707  INFO 37 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-05-06 18:10:44.755  WARN 37 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable
to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
2019-05-06 18:10:44.803  INFO 37 --- [main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-06 18:10:44.811 ERROR 37 --- [main] o.s.boot.SpringApplication               : Application run failed

**Comment by nobodyiam** [comment]
Spring的数据库连接信息会从几个地方加载

1. 配置文件中
2. -D参数
3. --程序参数
