### ISSUE TITLE
Request to apollo open api failed

### ISSUE THREAD

**Issue by fjc440** [ctripcorp/apollo#2229]
Caused by: com.ctrip.framework.apollo.openapi.client.exception.ApolloOpenApiException: Request to apollo open api failed, status code: 404, reason: , message: {"timestamp":"2019-05-14T10:42:44.412+0800","status":404,"error":"Not Found","message":"No message available","path":"/openapi/v1/envs/DEV/apps/sentinel-server/clusters/default/namespaces/application"}
	at com.ctrip.framework.apollo.openapi.client.service.AbstractOpenApiService.checkHttpResponseStatus(AbstractOpenApiService.java:99) ~[apollo-openapi-1.4.0.jar:1.4.0]
	at com.ctrip.framework.apollo.openapi.client.service.AbstractOpenApiService.execute(AbstractOpenApiService.java:80) ~[apollo-openapi-1.4.0.jar:1.4.0]
	at com.ctrip.framework.apollo.openapi.client.service.AbstractOpenApiService.get(AbstractOpenApiService.java:42) ~[apollo-openapi-1.4.0.jar:1.4.0]
	at com.ctrip.framework.apollo.openapi.client.service.NamespaceOpenApiService.getNamespace(NamespaceOpenApiService.java:39) ~[apollo-openapi-1.4.0.jar:1.4.0]
	... 64 common frames omitted

我看过之前一个问题是讲关于这个的，但是我的版本是1.1，却还是发生这样的问题？是不是url的路径不对？

**Comment by nobodyiam** [comment]
看一下portal的地址配置是否正确

**Comment by fjc440** [comment]
确实是这个问题，之前被版本误导了，后来自己仔细看了demo后确认了错误，谢谢
