### ISSUE TITLE
运行过程中SpringValueRegistry.scanAndClean一直报NullPointerException，可能是什么问题？

### ISSUE THREAD

**Issue by jim2017jim** [ctripcorp/apollo#2268]
`java.lang.NullPointerException
	at com.google.common.collect.LinkedListMultimap.removeNode(LinkedListMultimap.java:286)
	at com.google.common.collect.LinkedListMultimap.access$400(LinkedListMultimap.java:102)
	at com.google.common.collect.LinkedListMultimap$NodeIterator.remove(LinkedListMultimap.java:374)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.scanAndClean(SpringValueRegistry.java:70)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.access$000(SpringValueRegistry.java:16)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry$1.run(SpringValueRegistry.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by nobodyiam** [comment]
可能是并发所致，这个报错是偶发的还是频发？

**Comment by jim2017jim** [comment]
是客户端在运行过程中控制台会一直隔10分钟左右在后台打印该日志。
并不是所有的客户端都这样。目前是有个别客户端。
