### ISSUE TITLE
集成Apollo环境如何禁用

### ISSUE THREAD

**Issue by LuoLee** [ctripcorp/apollo#2311]
我们在`Spring Boot`项目中集成了`Apollo`，且也可以正常通过`Apollo`配置中心更新配置，但现在有一个问题，就是如何禁用`Apollo`，因为有一些情况下并没有配置中心环境。
已经配置了`apollo.bootstrap.enabled = false`，但还是定时的去配置中心轮询。
请问，如何才能完全的禁用`Apollo`？
配置了 `apollo.bootstrap.enabled = false` 时的应用日志如下：
```
[DEBUG] 2019-06-05 09:52:57.789 [Apollo-RemoteConfigRepository-1]   at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:208)
 - Loading config from http://10.200.30.59:8080/configs/zx/default/application?ip=172.16.14.2&messages=%7B%22details%22%3A%7B%22zx%2Bdefault%2Bapplication%22%3A31%7D%7D&releaseKey=20190515110300-a34c255e3ccbbd97
[DEBUG] 2019-06-05 09:52:57.794 [Apollo-RemoteConfigRepository-1]   at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:223)
 - Config server responds with 304 HTTP status code.
[DEBUG] 2019-06-05 09:53:00.209 [Apollo-RemoteConfigLongPollService-1]   at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(RemoteConfigLongPollService.java:172)
 - Long polling response: 304, url: http://10.200.30.59:8080/notifications/v2?cluster=default&appId=zx&ip=172.16.14.2&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A31%7D%5D
[DEBUG] 2019-06-05 09:53:00.210 [Apollo-RemoteConfigLongPollService-1]   at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(RemoteConfigLongPollService.java:163)
 - Long polling from http://10.200.30.59:8080/notifications/v2?cluster=default&appId=zx&ip=172.16.14.2&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A31%7D%5D
[DEBUG] 2019-06-05 09:53:09.545 [Eureka-JerseyClient-Conn-Cleaner2]   at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.closeIdleConnections(ThreadSafeClientConnManager.java:332)
 - Closing connections idle longer than 30000 SECONDS
[DEBUG] 2019-06-05 09:53:09.546 [Eureka-JerseyClient-Conn-Cleaner2]   at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.closeIdleConnections(ConnPoolByRoute.java:720)
 - Closing connections idle longer than 30000 SECONDS
[D
```

**Comment by LuoLee** [comment]
文档似乎提供了一种`-Denv=Local`的方式可以不从配置中心服务器获取配置，但这种方式应该还会从本地缓存配置文件读取配置，请问如何**完全**禁用呢？即既不从`Apollo服务器`获取配置，也不从本地缓存中获取配置，就像没有集成`Apollo`一样，所有配置项目从`application.yml`文件加载。

**Comment by nobodyiam** [comment]
apollo的配置启用方式有两个，目前如果需要完全禁用的话，就需要把下面配置去掉

1. `@EnableApolloConfig`
2. `apollo.bootstrap.enabled/apollo.bootstrap.namespaces`

**Comment by LuoLee** [comment]
OK，之前就是@EnableApolloConfig 注解没去掉导致的。

**Comment by HyberLinker** [comment]
> apollo的配置启用方式有两个，目前如果需要完全禁用的话，就需要把下面配置去掉
> 
> 1. `@EnableApolloConfig`
> 2. `apollo.bootstrap.enabled/apollo.bootstrap.namespaces`

没有使用注解，配置文件也没有配置apollo相关。但是仍然可以看到日志打印，并且还会定时拉取配置。请问这个怎么关掉

**Comment by HyberLinker** [comment]
> > apollo的配置启用方式有两个，目前如果需要完全禁用的话，就需要把下面配置去掉
> > 
> > 1. `@EnableApolloConfig`
> > 2. `apollo.bootstrap.enabled/apollo.bootstrap.namespaces`
> 
> 没有使用注解，配置文件也没有配置apollo相关。但是仍然可以看到日志打印，并且还会定时拉取配置。请问这个怎么关掉

找到原因了。因为使用了相关的listener ->ConfigChangeListener
