### ISSUE TITLE
按文档的方式引入公司的eureka总是提示错误

### ISSUE THREAD

**Issue by daiyongjun** [ctripcorp/apollo#2429]
环境: PRO
Active: false （当前环境状态异常，请结合下方系统信息和Admin Service的Check Health结果排查）
Meta server地址: http://qingbo:1111
Loading config/admin services from meta server: http://qingbo:1111 failed! Exception: 404

使用Configer自带的Eureka是没有问题
环境: DEV
Active: true
Meta server地址: http://qingbo:8080

自己是按文档步骤：1、修改configer的注解 2、修改configer数据库的erukeka地址 3、修改portal的环境引入；并确认了configer和admin服务都注册到http://qingbo:1111上，如

Application | AMIs | Availability Zones | Status
-- | -- | -- | --
APOLLO-ADMINSERVICE | n/a (1) | (1) | UP (1) - qingbo:apollo-adminservice:8091
APOLLO-CONFIGSERVICE | n/a (1) | (1) | UP (1) - qingbo:apollo-configservice:8081
EUREKA-SERVER | n/a (1) | (1) | UP (1) - qingbo:eureka-server:1111

但是还是
Loading config/admin services from meta server: http://qingbo:1111 failed! Exception: 404错误

2019-07-08 17:38:57.360 ERROR 24880 --- [Apollo-ServiceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: PRO, meta server address:http://qingbo:1111

org.springframework.web.client.HttpClientErrorException: 404 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:730)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:688)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:296)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:121)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:101)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:27)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lepdou** [comment]
你直接访问：http://qingbo:1111/services/admin , 然后看一下 config server 有没有错误日志

**Comment by daiyongjun** [comment]
访问http://qingbo:1111/services/admin 
提示404
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jul 09 08:59:39 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available
