### ISSUE TITLE
在k8s环境，低资源情况下,portal启用时日志报错

### ISSUE THREAD

**Issue by kentchenjh** [ctripcorp/apollo#2503]
在Deployment中限制cpu为0.5,内存1G，启动时会报一次错，不过之后就不会报错了，对使用无影响。

`com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://apollo-config-service.test.svc.cluster.local
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:175)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:93)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:59)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:126)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by kentchenjh** [comment]
看了源码，和PortalSettings时初始化后执行的线程池任务有关，稍微调大delay时间后，问题解决。https://github.com/ctripcorp/apollo/pull/2504

**Comment by nobodyiam** [comment]
这个错没啥影响的，portal会定期对admin service做health check，调大一些delay在你的环境上可以工作，不过本质上每个环境都不太一样的，所以感觉没啥必要
