### ISSUE TITLE
apollo 高可用环境部署失败

### ISSUE THREAD

**Issue by xichengliudui** [ctripcorp/apollo#2574]
部署方式为：容器部署，通过挂载配置文件启动，网络 --net=host
三个节点部署: `apollo-adminservice`
三个节点部署: `apollo-configservice`
一个节点部署: `apollo-portal`

adminservice 和 configservice 日志正常，如下所示
```
2019-09-05 16:27:32.188  INFO 37 --- [           main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8080
2019-09-05 16:27:32.243  INFO 37 --- [           main] c.c.f.a.c.ConfigServiceApplication       : Started ConfigServiceApplication in 65.058 seconds (JVM running for 67.496)
2019-09-05 16:27:32.246  INFO 37 --- [      Thread-17] e.s.EurekaServerInitializerConfiguration : Started Eureka Server
2019-09-05 16:27:36.236  INFO 37 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-09-05 16:27:36.236  INFO 37 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2019-09-05 16:27:36.520  INFO 37 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 283 ms
2019-09-05 16:28:32.137  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2019-09-05 16:29:32.138  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2019-09-05 16:30:32.138  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2019-09-05 16:31:32.137  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2019-09-05 16:32:32.138  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
2019-09-05 16:33:32.138  INFO 37 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
```
```
019-09-05 16:27:47.392  INFO 36 --- [           main] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
2019-09-05 16:27:47.418  INFO 36 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1567672067413 with initial instances count: 0
2019-09-05 16:27:47.487  INFO 36 --- [           main] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application apollo-adminservice with eureka with status UP
2019-09-05 16:27:47.595  INFO 36 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8090 (http) with context path ''
2019-09-05 16:27:47.597  INFO 36 --- [           main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8090
2019-09-05 16:27:47.605  INFO 36 --- [           main] c.c.f.a.a.AdminServiceApplication        : Started AdminServiceApplication in 63.329 seconds (JVM running for 66.993)
2019-09-05 16:27:51.942  INFO 36 --- [nio-8090-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-09-05 16:27:51.942  INFO 36 --- [nio-8090-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2019-09-05 16:27:52.020  INFO 36 --- [nio-8090-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 78 ms
```
apollo-portal 有异常日志
```
2019-09-05 16:39:26.853 ERROR 36 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 62, meta server address: http://192.168.1.138:8080
2019-09-05 16:39:36.854 ERROR 36 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://192.168.1.138:8080

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://192.168.1.138:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:172)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:90)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-09-05 16:39:36.854 ERROR 36 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 63, meta server address: http://192.168.1.138:8080
2019-09-05 16:39:46.855 ERROR 36 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://192.168.1.138:8080

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://192.168.1.138:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:172)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:90)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-09-05 16:39:46.856 ERROR 36 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 64, meta server address: http://192.168.1.138:8080
```

**Comment by xichengliudui** [comment]
访问任意 8080 端口如下
![image](https://user-images.githubusercontent.com/40875627/64326321-579b1400-cffc-11e9-8c24-95a9341a4e57.png)

**Comment by jiayaoO3O** [comment]
假设你docker里的adminserver的ip地址为10.2.x.x,这个时候如果你没有做任何额外的设置,那adminserver就会将这个10.2.x.x注册到eureka, 这个时候portal访问adminserver就会直接通过这个10.2.x.x访问,所以你要确保他们之间能不能用相互ping通,不然没法通过ip地址访问

**Comment by xichengliudui** [comment]
容器之间我是用的是 host 通信，宿主机之间的通信是没有问题的。就像下面
```
[root@eko137 ~]# ping 192.168.1.138
PING 192.168.1.138 (192.168.1.138) 56(84) bytes of data.
64 bytes from 192.168.1.138: icmp_seq=1 ttl=64 time=0.287 ms
64 bytes from 192.168.1.138: icmp_seq=2 ttl=64 time=0.248 ms
64 bytes from 192.168.1.138: icmp_seq=3 ttl=64 time=0.202 ms
64 bytes from 192.168.1.138: icmp_seq=4 ttl=64 time=0.248 ms
^C
--- 192.168.1.138 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.202/0.246/0.287/0.032 ms
[root@eko137 ~]# ping 192.168.1.139
PING 192.168.1.139 (192.168.1.139) 56(84) bytes of data.
64 bytes from 192.168.1.139: icmp_seq=1 ttl=64 time=0.223 ms
64 bytes from 192.168.1.139: icmp_seq=2 ttl=64 time=0.223 ms
64 bytes from 192.168.1.139: icmp_seq=3 ttl=64 time=0.261 ms
64 bytes from 192.168.1.139: icmp_seq=4 ttl=64 time=0.245 ms
^C
--- 192.168.1.139 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.223/0.238/0.261/0.016 ms

```

**Comment by xichengliudui** [comment]
请问还有什么会影响到 apollo，防护墙关闭状态，端口以开放！

**Comment by jiayaoO3O** [comment]
你的数据库里面的eureka的那一行有指定为configservice的地址吗?

**Comment by xichengliudui** [comment]
有的，内容如下：
```
http://192.168.1.137:8080/eureka/,http://192.168.1.138:8080/eureka/,http://192.168.1.139:8080/eureka/
```

**Comment by jiayaoO3O** [comment]
1.确保你在portal容器里面能够ping到这三个ip 192.168.1.137 , 192.168.1.138 , 192.168.1.139
2.在portal的配置文件config\apollo-env.properties的dev那一行写上上面三个ip地址
3.重新启动portal

**Comment by xichengliudui** [comment]
唯一不同的地方只有，config\apollo-env.properties 每一行我都配置了 ip 地址，是否是这里影响了 apollo
```
[root@eko137 ~]# docker exec -it 893a94d0b037 sh
/ # ping 192.168.1.137
PING 192.168.1.137 (192.168.1.137): 56 data bytes
64 bytes from 192.168.1.137: seq=0 ttl=64 time=0.171 ms
64 bytes from 192.168.1.137: seq=1 ttl=64 time=0.159 ms
64 bytes from 192.168.1.137: seq=2 ttl=64 time=0.136 ms
64 bytes from 192.168.1.137: seq=3 ttl=64 time=0.117 ms
^C
--- 192.168.1.137 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.117/0.145/0.171 ms
/ # ping 192.168.1.138 
PING 192.168.1.138 (192.168.1.138): 56 data bytes
64 bytes from 192.168.1.138: seq=0 ttl=64 time=2.954 ms
64 bytes from 192.168.1.138: seq=1 ttl=64 time=4.939 ms
64 bytes from 192.168.1.138: seq=2 ttl=64 time=6.234 ms
64 bytes from 192.168.1.138: seq=3 ttl=64 time=7.727 ms
64 bytes from 192.168.1.138: seq=4 ttl=64 time=3.999 ms
^C
--- 192.168.1.138 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 2.954/5.170/7.727 ms
/ # ping 192.168.1.139
PING 192.168.1.139 (192.168.1.139): 56 data bytes
64 bytes from 192.168.1.139: seq=0 ttl=64 time=2.281 ms
64 bytes from 192.168.1.139: seq=1 ttl=64 time=1.332 ms
64 bytes from 192.168.1.139: seq=2 ttl=64 time=5.964 ms
64 bytes from 192.168.1.139: seq=3 ttl=64 time=2.813 ms
64 bytes from 192.168.1.139: seq=4 ttl=64 time=3.992 ms
64 bytes from 192.168.1.139: seq=5 ttl=64 time=4.001 ms
^C
--- 192.168.1.139 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 1.332/3.397/5.964 ms
/ # cat -n apollo-portal/config/apollo-env.properties 
     1	local.meta=http://192.168.1.137:8080,http://192.168.1.138:8080,http://192.168.1.139:8080
     2	dev.meta=http://192.168.1.137:8080,http://192.168.1.138:8080,http://192.168.1.139:8080
     3	fat.meta=http://192.168.1.137:8080,http://192.168.1.138:8080,http://192.168.1.139:8080
     4	uat.meta=http://192.168.1.137:8080,http://192.168.1.138:8080,http://192.168.1.139:8080
     5	lpt.meta=${lpt_meta}
     6	pro.meta=http://192.168.1.137:8080,http://192.168.1.138:8080,http://192.168.1.139:8080

```

**Comment by xichengliudui** [comment]
结果仍然是这样
![1567675420(1)](https://user-images.githubusercontent.com/40875627/64329482-ee1e0400-d001-11e9-89eb-05248d580ae3.png)

**Comment by jiayaoO3O** [comment]
按理来说,需要配置的地方也就这么几个了:
1. configdb数据库的eureka那一行要写上同一开发环境例如Dev所有的configservice的IP地址.
2.portal的apollo-env.properties 中对应的位置要写上同一环境所有的configservice的IP地址.
这样之后,只要确保网络是可以互相访问的,那就可以向eureka注册自己了.
所以你试试把apollo-env.properties 里面除了dev的都注释掉试试.

**Comment by xichengliudui** [comment]
ok，thanks 我去试一下

**Comment by jiayaoO3O** [comment]
按理来说哪怕portal启动失败,eureka里面也会有各个configservice和adminservice的注册信息的,现在连这个注册信息都没有出现,我还是倾向容器之间没有能够互相访问.你一定要确保adminservice容器,configservice容器,portal容器能够两两互相ping通

**Comment by jiayaoO3O** [comment]
甚至你可以`docker ps`看看容器是不是挂了

**Comment by xichengliudui** [comment]
绝望......

**Comment by jiayaoO3O** [comment]
你可以试试先只启动一个configservice和一个adminservice,然后看看8080的信息,看看有没有注册成功

**Comment by xichengliudui** [comment]
找到问题的根源了，我运行 admin、config 会抛出下面的错误
```
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
```

所以在配置文件中添加了下面内容

```
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
```

导致了一直失败！

**Comment by xichengliudui** [comment]
成功！失败就是因为配置了上面两行内容！但是如果抛出了错误，又不得不配置
![1567678803(1)](https://user-images.githubusercontent.com/40875627/64333749-cf237000-d009-11e9-9d9b-a2d8e0e5bc47.png)

**Comment by jiayaoO3O** [comment]
![image](https://user-images.githubusercontent.com/22891632/64334987-68538600-d00c-11e9-829e-a1b9cb022ef1.png)

**Comment by xichengliudui** [comment]
气的拍桌子

**Comment by cuishuang** [comment]
解决了吗
