### ISSUE TITLE
apollo spring 自动更新配置异常 1.5.0

### ISSUE THREAD

**Issue by wu560130911** [ctripcorp/apollo#2692]
apollo会自动更新占位符的变量，当更新以下值的时候，存在异常，麻烦看看；
2019-10-24 11:40:18,725 - spring.property.AutoUpdateConfigChangeListener [Apollo-Config-4] ERROR spring.property.AutoUpdateConfigChangeListener(74) []  - Auto update apollo changed value failed, key: master.url, beanName: dataSource, method: com.alibaba.druid.pool.DruidDataSource.setUrl
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at com.ctrip.framework.apollo.spring.property.SpringValue.injectMethod(SpringValue.java:80) ~[apollo-client-1.5.0-20191022.094954-10.jar:1.5.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spring.property.SpringValue.update(SpringValue.java:59) ~[apollo-client-1.5.0-20191022.094954-10.jar:1.5.0-SNAPSHOT]
	at com.ctrip.framework.apollo.spring.property.AutoUpdateConfigChangeListener.updateSpringValue(AutoUpdateConfigChangeListener.java:69) [apollo-client-1.5.0-20191022.094954-10.jar:1.5.0-SNAPSHOT]

**Comment by g5niusx** [comment]
能提供一下apollo的配置吗？还有对应的client如何使用的。😄

**Comment by nobodyiam** [comment]
看代码DruidDataSource不允许多次setUrl

https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/pool/DruidAbstractDataSource.java#L1185

![image](https://user-images.githubusercontent.com/837658/67644254-dd7f6f80-f95a-11e9-897e-c8a518b20cec.png)

**Comment by wu560130911** [comment]
是的，有办法针对特定ns不自动更新么

**Comment by nobodyiam** [comment]
这个可能得讨论下，是基于特定ns不自动更新还是基于某个key不自动更新
