### ISSUE TITLE
dubbo使用apollo做动态配置中心出现问题：出现了dubbo.properties.properties、dubbo.properties.properties.properties

### ISSUE THREAD

**Issue by makingtime** [ctripcorp/apollo#2702]
dubbo版本：2.7.4.1
apollo版本：1.5.0

dubbo spring boot应用的application.properties内容
```
app.id = 1001
apollo.meta = http://xxx.xxx:18080
apollo.cacheDir = ./config
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application
dubbo.config-center.address=apollo://xxx.xxx:18080
```

apollo中只使用了DEV环境，新建了一个应用
具体配置如下

![image](https://user-images.githubusercontent.com/53243647/67670126-2d3b5680-f9ae-11e9-8791-776065b62966.png)

根据dubbo 2.7.4.1的一个PR：https://github.com/apache/dubbo/pull/5105
现在dubbo是使用apollo的一个namespace对应一个配置文件的这种模型的

启动参数加了-Denv=DEV

启动过程中报错：
```
2019-10-28 18:02:42.465 [main] WARN  com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: 1001, cluster: default, namespaces: dubbo.properties.properties
2019-10-28 18:02:43.488 [main] WARN  com.ctrip.framework.apollo.internals.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: 1001, cluster: default, namespace: dubbo.properties.properties, url: http://172.16.11.202:18080/configs/1001/default/dubbo.properties.properties?ip=172.16.10.11 [Cause: [status code: 404] Could not find config for namespace - appId: 1001, cluster: default, namespace: dubbo.properties.properties, please check whether the configs are released in Apollo!]
2019-10-28 18:02:43.509 [main] WARN  com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: 1001, cluster: default, namespaces: dubbo.properties.properties
2019-10-28 18:02:44.522 [main] WARN  com.ctrip.framework.apollo.internals.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: 1001, cluster: default, namespace: dubbo.properties.properties, url: http://172.16.11.202:18080/configs/1001/default/dubbo.properties.properties?ip=172.16.10.11 [Cause: [status code: 404] Could not find config for namespace - appId: 1001, cluster: default, namespace: dubbo.properties.properties, please check whether the configs are released in Apollo!]
2019-10-28 18:02:44.531 [main] WARN  com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: 1001, cluster: default, namespaces: dubbo.properties.properties
2019-10-28 18:02:45.543 [main] WARN  com.ctrip.framework.apollo.internals.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: 1001, cluster: default, namespace: dubbo.properties.properties, url: http://172.16.11.202:18080/configs/1001/default/dubbo.properties.properties?ip=172.16.10.11 [Cause: [status code: 404] Could not find config for namespace - appId: 1001, cluster: default, namespace: dubbo.properties.properties, please check whether the configs are released in Apollo!]
2019-10-28 18:02:45.544 [main] WARN  com.ctrip.framework.apollo.internals.AbstractConfigRepository - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.LocalFileConfigRepository, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\Develop\projects\dubbo-consumer-a\.\config\1001\config-cache\1001+default+dubbo.properties.properties.properties]
2019-10-28 18:02:45.556 [main] WARN  com.ctrip.framework.apollo.internals.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: 1001, cluster: default, namespaces: dubbo.properties.properties
2019-10-28 18:02:46.570 [main] WARN  com.ctrip.framework.apollo.internals.LocalFileConfigRepository - Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: 1001, cluster: default, namespace: dubbo.properties.properties, url: http://172.16.11.202:18080/configs/1001/default/dubbo.properties.properties?ip=172.16.10.11 [Cause: [status code: 404] Could not find config for namespace - appId: 1001, cluster: default, namespace: dubbo.properties.properties, please check whether the configs are released in Apollo!]
2019-10-28 18:02:46.571 [main] WARN  com.ctrip.framework.apollo.internals.AbstractConfigFile - Init Apollo Config File failed - namespace: dubbo.properties.properties, reason: Load config from local config failed! [Cause: Cannot read from local cache file C:\Develop\projects\dubbo-consumer-a\.\config\1001\config-cache\1001+default+dubbo.properties.properties.properties].
2019-10-28 18:02:46.580 [main] WARN  org.apache.dubbo.common.config.ConfigurationUtils -  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.4.1, current host: 172.16.10.11
2019-10-28 18:02:46.580 [main] WARN  org.apache.dubbo.common.config.ConfigurationUtils -  [DUBBO] You specified the config centre, but there's not even one single config item in it., dubbo version: 2.7.4.1, current host: 172.16.10.11
2019-10-28 18:02:46.594 [main] WARN  org.apache.dubbo.config.AbstractConfig -  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.4.1, current host: 172.16.10.11
2019-10-28 18:02:46.635 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboConsumerController': Injection of @Reference dependencies is failed; nested exception is java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />
```
最后应用退出
```
2019-10-28 18:02:46.676 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-10-28 18:02:46.678 [main] INFO  org.apache.dubbo.spring.boot.context.event.AwaitingNonWebApplicationListener -  [Dubbo] Current Spring Boot Application is about to shutdown...
2019-10-28 18:02:46.692 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboConsumerController': Injection of @Reference dependencies is failed; nested exception is java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:150) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) [spring-boot-2.1.7.RELEASE.jar:2.1.7.RELEASE]
	at com.test.consumer_a.DubboConsumerApplication.main(DubboConsumerApplication.java:13) [classes/:?]
Caused by: java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkRegistry(AbstractInterfaceConfig.java:203) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:378) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:329) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:250) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.getOrCreateProxy(ReferenceAnnotationBeanPostProcessor.java:246) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:143) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.getInjectedObject(AnnotationInjectedBeanPostProcessor.java:359) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor$AnnotatedFieldElement.inject(AnnotationInjectedBeanPostProcessor.java:539) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:146) ~[dubbo-2.7.4.1.jar:2.7.4.1]
	... 17 more
Disconnected from the target VM, address: '127.0.0.1:55529', transport: 'socket'

Process finished with exit code 1
```

通过断点调试，发现在`com.ctrip.framework.apollo.internals.DefaultConfigManager`的getConfigFile(String namespace, ConfigFileFormat configFileFormat)方法中调用createConfigFile的传参(第58行)可能有问题，

我把DefaultConfigManager复制到src下同样的包路径下，把传入`namespaceFileName`改为传入`namespace`,这个错误就消失了

**Comment by nobodyiam** [comment]
看这个描述应该是dubbo传入的namespace名字不对，应该是`getConfigFile("dubbo", ConfigFileFormat.Properties)`

**Comment by makingtime** [comment]
确实好像是dubbo那个PR没改全？断点处(`com.ctrip.framework.apollo.internals.RemoteConfigRepository`构造函数第一行)前几次的值都是正常的"application"、"dubbo"，第4次就变成"dubbo.properties"了, 对应的堆栈是：

```java
<init>:79, RemoteConfigRepository (com.ctrip.framework.apollo.internals)
createRemoteConfigRepository:77, DefaultConfigFactory (com.ctrip.framework.apollo.spi)
createLocalConfigRepository:73, DefaultConfigFactory (com.ctrip.framework.apollo.spi)
createConfigFile:47, DefaultConfigFactory (com.ctrip.framework.apollo.spi)
getConfigFile:58, DefaultConfigManager (com.ctrip.framework.apollo.internals)
getConfigFile:65, ConfigService (com.ctrip.framework.apollo)
getProperties:155, ApolloDynamicConfiguration (org.apache.dubbo.configcenter.support.apollo)
getProperties:110, DynamicConfiguration (org.apache.dubbo.configcenter)
prepareEnvironment:291, AbstractInterfaceConfig (org.apache.dubbo.config)
startConfigCenter:280, AbstractInterfaceConfig (org.apache.dubbo.config)
checkAndUpdateSubConfigs:220, ReferenceConfig (org.apache.dubbo.config)
get:244, ReferenceConfig (org.apache.dubbo.config)
getOrCreateProxy:246, ReferenceAnnotationBeanPostProcessor (org.apache.dubbo.config.spring.beans.factory.annotation)
doGetInjectedBean:143, ReferenceAnnotationBeanPostProcessor (org.apache.dubbo.config.spring.beans.factory.annotation)
getInjectedObject:359, AnnotationInjectedBeanPostProcessor (org.apache.dubbo.config.spring.beans.factory.annotation)
inject:539, AnnotationInjectedBeanPostProcessor$AnnotatedFieldElement (org.apache.dubbo.config.spring.beans.factory.annotation)
inject:90, InjectionMetadata (org.springframework.beans.factory.annotation)
postProcessPropertyValues:146, AnnotationInjectedBeanPostProcessor (org.apache.dubbo.config.spring.beans.factory.annotation)
populateBean:1416, AbstractAutowireCapableBeanFactory (org.springframework.beans.factory.support)
doCreateBean:592, AbstractAutowireCapableBeanFactory (org.springframework.beans.factory.support)
createBean:515, AbstractAutowireCapableBeanFactory (org.springframework.beans.factory.support)
lambda$doGetBean$0:320, AbstractBeanFactory (org.springframework.beans.factory.support)
getObject:-1, 1031775150 (org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$141)
getSingleton:222, DefaultSingletonBeanRegistry (org.springframework.beans.factory.support)
doGetBean:318, AbstractBeanFactory (org.springframework.beans.factory.support)
getBean:199, AbstractBeanFactory (org.springframework.beans.factory.support)
preInstantiateSingletons:845, DefaultListableBeanFactory (org.springframework.beans.factory.support)
finishBeanFactoryInitialization:877, AbstractApplicationContext (org.springframework.context.support)
refresh:549, AbstractApplicationContext (org.springframework.context.support)
refresh:141, ServletWebServerApplicationContext (org.springframework.boot.web.servlet.context)
refresh:743, SpringApplication (org.springframework.boot)
refreshContext:390, SpringApplication (org.springframework.boot)
run:312, SpringApplication (org.springframework.boot)
run:1214, SpringApplication (org.springframework.boot)
run:1203, SpringApplication (org.springframework.boot)
main:13, DubboConsumerApplication (com.test.consumer_a)
```

`getProperties:155, ApolloDynamicConfiguration (org.apache.dubbo.configcenter.support.apollo)`这里传入的时候已经是：`ConfigService.getConfigFile("dubbo.properties", ConfigFileFormat.Properties);`了
