### ISSUE TITLE
ClassNotFoundException: com.fasterxml.jackson

### ISSUE THREAD

**Issue by nisiyong** [ctripcorp/apollo#2753]
## 环境
- MacOS 10.14.6
- Java version: 1.8.0_181, vendor: Oracle Corporation
- Apache Maven 3.6.1

## 问题

下载代码后，切到最新tag
```
git checkout v1.5.1
```

按照[Apollo开发指南](https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97)操作配置，运行`com.ctrip.framework.apollo.assembly.ApolloApplication`，配置如下：

![image](https://user-images.githubusercontent.com/8198862/68593082-98694a80-04cf-11ea-90fc-9726af328482.png)

异常栈信息如下：
```
18:34:15,730 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:34:15,731 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
18:34:15,731 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/nisiyong/CodeProjects/apollo/apollo-assembly/target/classes/logback.xml]
18:34:15,732 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
18:34:15,732 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/nisiyong/CodeProjects/apollo/apollo-configservice/target/classes/logback.xml]
18:34:15,732 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/nisiyong/CodeProjects/apollo/apollo-assembly/target/classes/logback.xml]
18:34:15,732 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/nisiyong/CodeProjects/apollo/apollo-portal/target/classes/logback.xml]
18:34:15,732 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/nisiyong/CodeProjects/apollo/apollo-adminservice/target/classes/logback.xml]
18:34:15,806 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
18:34:15,812 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@5c3bd550 - Adding [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
18:34:15,812 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@91161c7 - URL [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
18:34:15,815 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
18:34:15,815 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
18:34:15,815 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.startup.DigesterFactory] to ERROR
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.util.LifecycleBase] to ERROR
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.coyote.http11.Http11NioProtocol] to WARN
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.sshd.common.util.SecurityUtils] to WARN
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.tomcat.util.net.NioSelectorPool] to WARN
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty.util.component.AbstractLifeCycle] to ERROR
18:34:15,820 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate.validator.internal.util.Version] to WARN
18:34:15,821 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@5c3bd550 - Adding [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/file-appender.xml] to configuration watch list.
18:34:15,821 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@91161c7 - URL [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/file-appender.xml] is not of type file
18:34:15,822 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
18:34:15,828 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
18:34:15,836 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:34:15,896 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1615780336 - Archive files will be limited to [10 MB] each.
18:34:15,900 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1615780336 - Will use gz compression
18:34:15,901 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1615780336 - Will use the pattern /var/folders/mm/wx8xn5w96sx3p8vcl7703lf40000gn/T//apollo-assembly.log.%d{yyyy-MM-dd}.%i for the active file
18:34:15,904 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6a4f787b - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/folders/mm/wx8xn5w96sx3p8vcl7703lf40000gn/T//apollo-assembly.log.%d{yyyy-MM-dd}.%i.gz'.
18:34:15,904 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6a4f787b - Roll-over at midnight.
18:34:15,907 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6a4f787b - Setting initial period to Sun Nov 10 15:56:19 CST 2019
18:34:15,916 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /var/folders/mm/wx8xn5w96sx3p8vcl7703lf40000gn/T//apollo-assembly.log
18:34:15,917 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/var/folders/mm/wx8xn5w96sx3p8vcl7703lf40000gn/T//apollo-assembly.log]
18:34:15,918 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@5c3bd550 - Adding [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/console-appender.xml] to configuration watch list.
18:34:15,918 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@91161c7 - URL [jar:file:/Users/nisiyong/.m2/repository/org/springframework/boot/spring-boot/2.0.5.RELEASE/spring-boot-2.0.5.RELEASE.jar!/org/springframework/boot/logging/logback/console-appender.xml] is not of type file
18:34:15,919 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:34:15,921 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
18:34:15,922 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:34:15,925 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
18:34:15,926 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
18:34:15,926 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
18:34:15,926 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:34:15,927 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@685cb137 - Registering current configuration as safe fallback point

2019-11-11 18:34:26.573  INFO 66984 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5acf93bb: startup date [Mon Nov 11 18:34:26 CST 2019]; root of context hierarchy
2019-11-11 18:34:26.752  INFO 66984 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-11-11 18:34:26.777  INFO 66984 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$2385cf88] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
     _                _ _
    / \   _ __   ___ | | | ___
   / _ \ | '_ \ / _ \| | |/ _ \
  / ___ \| |_) | (_) | | | (_) |
 /_/   \_\ .__/ \___/|_|_|\___/
         |_|

:: Spring Boot ::  (v2.0.5.RELEASE)

2019-11-11 18:34:36.920  INFO 66984 --- [           main] c.c.f.apollo.assembly.ApolloApplication  : The following profiles are active: github
2019-11-11 18:34:36.932  INFO 66984 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@67304a40: startup date [Mon Nov 11 18:34:36 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5acf93bb
2019-11-11 18:34:37.577  INFO 66984 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=d46dc221-790d-3963-88ab-0b0a3ebf8f10
2019-11-11 18:34:37.591  INFO 66984 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-11-11 18:34:37.697  INFO 66984 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$2385cf88] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-11-11 18:34:37.737  WARN 66984 --- [           main] o.s.c.n.a.ArchaiusAutoConfiguration      : No spring.application.name found, defaulting to 'application'
2019-11-11 18:34:37.741  WARN 66984 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-11-11 18:34:37.741  INFO 66984 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-11-11 18:34:37.746  WARN 66984 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2019-11-11 18:34:37.746  INFO 66984 --- [           main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-11-11 18:34:37.856  INFO 66984 --- [           main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
2019-11-11 18:34:38.077  WARN 66984 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesReportEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/context/properties/ConfigurationPropertiesReportEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.context.properties.ConfigurationPropertiesReportEndpoint]: Factory method 'configurationPropertiesReportEndpoint' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/BeanSerializerModifier
2019-11-11 18:34:38.086  INFO 66984 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-11-11 18:34:38.089 ERROR 66984 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationPropertiesReportEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/context/properties/ConfigurationPropertiesReportEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.context.properties.ConfigurationPropertiesReportEndpoint]: Factory method 'configurationPropertiesReportEndpoint' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/BeanSerializerModifier
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:590)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.ctrip.framework.apollo.assembly.ApolloApplication.main(ApolloApplication.java:28)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.context.properties.ConfigurationPropertiesReportEndpoint]: Factory method 'configurationPropertiesReportEndpoint' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/BeanSerializerModifier
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
	... 16 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/BeanSerializerModifier
	at org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration.configurationPropertiesReportEndpoint(ConfigurationPropertiesReportEndpointAutoConfiguration.java:50)
	at org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$63ee8596.CGLIB$configurationPropertiesReportEndpoint$0(<generated>)
	at org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$63ee8596$$FastClassBySpringCGLIB$$89ff6e8a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
	at org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration$$EnhancerBySpringCGLIB$$63ee8596.configurationPropertiesReportEndpoint(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.BeanSerializerModifier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 common frames omitted
```

**Comment by nisiyong** [comment]
Sorry，找到原因了。是因为maven local repo的问题，虽然不知道是什么原因导致下载的文件是空的。
但是删除后重新拉去依赖就好了。我先close issue了

```
➜  jackson-databind cd 2.9.6
➜  2.9.6 ll
total 40
-rw-r--r--  1 nisiyong  staff   273B  8 15  2018 _remote.repositories
-rw-r--r--  1 nisiyong  staff     0B  8 13  2018 jackson-databind-2.9.6.jar
-rw-r--r--  1 nisiyong  staff    40B  8 13  2018 jackson-databind-2.9.6.jar.sha1
-rw-r--r--  1 nisiyong  staff   6.2K  8 13  2018 jackson-databind-2.9.6.pom
-rw-r--r--  1 nisiyong  staff    40B  8 13  2018 jackson-databind-2.9.6.pom.sha1
```
