### ISSUE TITLE
1.3.0 release版 无法创建公共namespace

### ISSUE THREAD

**Issue by LimTerran** [ctripcorp/apollo#2852]
使用1.3.0版，创建公共namespace时，出现下面图片中的问题

![image](https://user-images.githubusercontent.com/24284961/71087152-6fc32780-21d6-11ea-9bd1-02f51ad024ce.png)

环境：centos7，
MySQL：5.7.22 Percona Server

查看portal log，显示内容为表单验证异常，还请检查一下实体类的验证规则

2019-12-18 20:12:28.247 ERROR 2618 --- [nio-8070-exec-7] .c.f.a.c.c.GlobalDefaultExceptionHandler : Validation failed for classes [com.ctrip.framework.apollo.common.entity.AppNamespace] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Namespace格式错误: 只允许输入数字，字母和符号 - _ . & 不允许以.json, .yml, .yaml, .xml, .properties结尾', propertyPath=name, rootBeanClass=class com.ctrip.framework.apollo.common.entity.AppNamespace, messageTemplate='Namespace格式错误: 只允许输入数字，字母和符号 - _ . & 不允许以.json, .yml, .yaml, .xml, .properties结尾'}
]

com.ctrip.framework.apollo.common.exception.BadRequestException: Validation failed for classes [com.ctrip.framework.apollo.common.entity.AppNamespace] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='Namespace格式错误: 只允许输入数字，字母和符号 - _ . & 不允许以.json, .yml, .yaml, .xml, .properties结尾', propertyPath=name, rootBeanClass=class com.ctrip.framework.apollo.common.entity.AppNamespace, messageTemplate='Namespace格式错误: 只允许输入数字，字母和符号 - _ . & 不允许以.json, .yml, .yaml, .xml, .properties结尾'}
]
	at com.ctrip.framework.apollo.common.controller.GlobalDefaultExceptionHandler.handleConstraintViolationException(GlobalDefaultExceptionHandler.java:92)
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by LimTerran** [comment]
是由部门名称中包含"&"符号导致，若自动勾选部门作为前缀，则会出现上述问题

**Comment by nobodyiam** [comment]
是的，部门名称中不要出现特殊符号吧
