### ISSUE TITLE
load env:DEV cluster error.404 Not Found

### ISSUE THREAD

**Issue by jiangxiaoqiang** [ctripcorp/apollo#3080]
**Describe the bug**

DEV环境通过域名映射到公网后提示，load env:DEV cluster error.404 Not Found。获取DEV环境时提示，补缺环境时也是同样的提示。客户端可以正常连接，只能用以前添加的配置，无法新增新的配置。

Apollo版本：1.6.0

虽然有相同的Issue，但是都没有说明是如何解决，问题出现的原因。

![image](https://user-images.githubusercontent.com/4521375/82149225-2e1fd100-9889-11ea-8d5d-8f162d612807.png)

后端日志：

```
2020-05-17 21:31:05.135 ERROR 24 --- [nio-8070-exec-4] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: /apps/0010020003, method: GET
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:730)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:688)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:296)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:197)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:102)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:63)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$AppAPI.loadApp(AdminServiceAPI.java:35)
	at com.ctrip.framework.apollo.portal.service.AppService.load(AppService.java:99)

```

**Comment by Anilople** [comment]
哪个组件出问题，client，portal，config，还是admin？

portal上可以检查一下

**Comment by nobodyiam** [comment]
看一下admin service的日志

**Comment by eqhi1314** [comment]
问题解决了吗？

**Comment by HMConnie** [comment]
解决了吗，同样遇到这个问题了~

**Comment by aotuzhao** [comment]
一模一样，有解决方案了吗

**Comment by eqhi1314** [comment]
已经解决了

发自我的iPhone

**Comment by xiamaoxuan** [comment]
怎么解决的？？

**Comment by tianqing108** [comment]
怎么解决的呢？Apollo真的好坑，bug贼多

**Comment by zywj** [comment]
里面的端口也要映射出来。@tianqing108   @xiamaoxuan

apollo-configservice:

```
docker run -p 8858:8858 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://192.168.31.31:3306/ApolloConfigDB?characterEncoding=utf8" \
    -e SERVER_PORT=8858 \
    -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=123 \
    -e EUREKA_INSTANCE_IP_ADDRESS=192.168.31.31 \
    -e EUREKA_SERVICE_URL=http://192.168.31.31:8858/eureka \
    -d  --name apollo-configservice apolloconfig/apollo-configservice

```

apollo-adminservice: 

```
docker run -p 8868:8868 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://192.168.31.31:3306/ApolloConfigDB?characterEncoding=utf8" \
    -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=123 \
    -e SERVER_PORT=8868 \
    -e EUREKA_INSTANCE_IP_ADDRESS=192.168.31.31 \
    -e EUREKA_SERVICE_URL=http://192.168.31.31:8858/eureka \
    -d --name apollo-adminservice apolloconfig/apollo-adminservice
```

apollo-portalservice:

```
docker run -p 8070:8070 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://192.168.31.31:3306/ApolloPortalDB?characterEncoding=utf8" \
    -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=123 \
    -e APOLLO_PORTAL_ENVS=dev \
    -e DEV_META=http://192.168.31.31:8858 \
    -d --name apollo-portal apolloconfig/apollo-portal
```

**Comment by maxiaotian0730** [comment]
怎么解决的，端口都映射出来了，/services/admin 可以正常通行，check health也正常，
admin无异常日志，这个错误到底怎么回事

**Comment by maxiaotian0730** [comment]
> 看一下admin service的日志

端口都映射出来了，/services/admin 可以正常通信，check health也正常，
admin无异常日志，这个错误到底怎么回事

**Comment by lzyinan** [comment]
同样的问题，阿里云搭了一套Apollo 1.6.1，springboot应用部署在k8s，通过application.yml配置文件的方式从meta拉取配置，项目启动的时候能拉取到，但是后面5分钟定时同步一直报错：
c.c.f.apollo.internals.AbstractConfigRepository:29 - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: test, cluster: testing3, namespace: application, url: http://ip:port/configs/test/testing3/application?ip=10.210.*.*&releaseKey=20210630105331-release [Cause: [status code: 404] Could not find config for namespace - appId: test, cluster: testing3, namespace: application, please check whether the configs are released in Apollo!]
隐去了ip和appid，有大佬能帮解决一下吗

**Comment by jiangxiaoqiang** [comment]
解决了，但是忘记是怎么解决的了。我的是部署在Kubernetes 1.15里面的。看日志应该可以找到问题原因，apollo目前用起来还是非常稳定的。
