### ISSUE TITLE
灰度发布交叉拉取配置。一会儿拉取主版本一会拉取灰度版本是为什么？

### ISSUE THREAD

**Issue by Deep2018530** [ctripcorp/apollo#3288]
问题：
一台灰度实例希望拉取灰度配置，但是通过日志可以发现Apollo交叉拉取了主版本/灰度版本配置，请问这块有什么可能的因素导致的呢？

我们test、beta都没问题，prod（prod5个节点）出现的这种问题，暂时没有头绪。
主版本：20  灰度版本：40
这个时间差也很诡异

![image](https://user-images.githubusercontent.com/39756103/92346331-fcb06700-f0fe-11ea-8f5b-5dd7753063f3.png)

**Comment by Deep2018530** [comment]
定位到问题了。。。
有个别节点，灰度规则扫描写缓存转json的时候报错了。
所以服务端无法从灰度规则里确认客户端有灰度，就给的主版本配置。也就证明了为什么交错时间是5分钟的倍数，一切都看客户端轮询到好的节点还是有问题的节点了。

java.lang.NoClassDefFoundError: com/google/gson/internal/ConstructorConstructor$6
	at com.google.gson.internal.ConstructorConstructor.newDefaultImplementationConstructor(ConstructorConstructor.java:158)
	at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:88)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:54)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.fromJson(Gson.java:886)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.ctrip.framework.apollo.common.utils.GrayReleaseRuleItemTransformer.batchTransformFromJSON(GrayReleaseRuleItemTransformer.java:20)
	at com.ctrip.framework.apollo.biz.grayReleaseRule.GrayReleaseRulesHolder.transformRuleToRuleCache(GrayReleaseRulesHolder.java:237)
	at com.ctrip.framework.apollo.biz.grayReleaseRule.GrayReleaseRulesHolder.mergeGrayReleaseRules(GrayReleaseRulesHolder.java:196)
	at com.ctrip.framework.apollo.biz.grayReleaseRule.GrayReleaseRulesHolder.handleMessage(GrayReleaseRulesHolder.java:100)
	at com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner.fireMessageScanned(ReleaseMessageScanner.java:116)
	at com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner.scanAndSendMessages(ReleaseMessageScanner.java:93)
	at com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner.scanMessages(ReleaseMessageScanner.java:77)
	at com.ctrip.framework.apollo.biz.message.ReleaseMessageScanner.lambda$afterPropertiesSet$0(ReleaseMessageScanner.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
