### ISSUE TITLE
portal启动报错找不到admin server，但是却能登陆界面

### ISSUE THREAD

**Issue by gongjing123** [ctripcorp/apollo#3338]
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.186.245.239:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:212)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:116)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:82)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:27)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:132)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2020-10-17 17:04:21.488 ERROR 28216 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed for 1 times which less than down threshold. down threshold:2, env: DEV, meta server address: http://10.186.245.239:8080

**Comment by gongjing123** [comment]
http://10.186.245.239:8080/services/admin也能正常访问

**Comment by nobodyiam** [comment]
看一下 http://10.186.245.239:8080/services/admin 的响应结果，里面的 ip 是否 portal 能连通？

**Comment by gongjing123** [comment]
响应结果正常：[{"appName":"APOLLO-ADMINSERVICE","instanceId":"file-storage:apollo-adminservice:8090","homepageUrl":"http://10.186.245.239:8090/"}]  系统信息 页面也没有报错  目前也没发现使用有什么影响，但portal启动确实有打印报错

**Comment by nobodyiam** [comment]
看下 管理员工具 - 系统信息 页面呢？上面可以对这台admin service做check health

**Comment by gongjing123** [comment]
check health 一切都没问题，所以就很疑惑   至今也没找到有没有影响

**Comment by nobodyiam** [comment]
@gongjing123 看你这个日志，应该 DEV 环境会不展示的，或者说这个日志只是间歇出现吗？

**Comment by ws0406** [comment]
通过docker-quick-start安装，遇到相同问题，页面中的环境列表为空，没有DEV环境，上面的报错信息每隔一段时间报一次

**Comment by nobodyiam** [comment]
@ws0406 进入管理员工具 - 系统信息页面看下
