### ISSUE TITLE
load env :DEV cluster error.404 Not Found

### ISSUE THREAD

**Issue by tianqing108** [ctripcorp/apollo#3400]
apollo-portal一直报这个错误怎么解决？配置可以正常使用，但是没法加新的配置了
eureka使用configservice和adminservice的节点的，apollo-portal的health-check是正常的，有谁知道咋解决吗？
![image](https://user-images.githubusercontent.com/66669730/100330071-70308900-3009-11eb-9bea-7dc5c2b4ce9b.png)

报了这个错：
c.c.f.a.p.c.RetryableRestTemplate : Http request failed, uri: /apps/demo-web/clusters, method: GET

org.springframework.web.client.HttpClientErrorException: 404

at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)

at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)

at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)

at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:730)

at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:688)

at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)

**Comment by nobodyiam** [comment]
看一下 admin service 的日志
