### ISSUE TITLE
改为nacos注册中心 后启动portal 轮询configService报401

### ISSUE THREAD

**Issue by X-Zackt** [ctripcorp/apollo#3653]
我将configservice,adminservice全部改为外部nacos注册中心，启动没问题后，在去启动portal,一直轮询报错如下：

2021-04-28 16:08:26.515 ERROR 18060 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://10.66.84.106:8080

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.66.84.106:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:212)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:116)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:82)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:27)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:132)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2021-04-28 16:08:26.516 ERROR 18060 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed for 1 times which less than down threshold. down threshold:2, env: DEV, meta server address: http://10.66.84.106:8080
Disconnected from the target VM, address: '127.0.0.1:64896', transport: 'socket'
2021-04-28 16:08:50.688 ERROR 18060 --- [erviceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: DEV, meta server address:http://10.66.84.106:8080

org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : [{"timestamp":"2021-04-28T16:08:26.712+0800","status":401,"error":"Unauthorized","message":"","path":"/services/admin"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:818)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:333)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:125)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:105)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:27)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

启动参数如下：
-Dapollo_profile=github,auth
-Ddev_meta=http://10.66.84.106:8080
-Dserver.port=8070
-Dspring.datasource.url=jdbc:mysql://xx:3306/ApolloPortalDB?characterEncoding=utf8
-Dspring.datasource.username=root
-Dspring.datasource.password=

**Comment by nobodyiam** [comment]
看报错日志是访问 http://10.66.84.106:8080/services/admin 报 401 了，不过 config service 中应该没有这部分逻辑，你先访问 http://10.66.84.106:8080 看看是不是 config service 的页面？

**Comment by X-Zackt** [comment]
> 看报错日志是访问 http://10.66.84.106:8080/services/admin 报 401 了，不过 config service 中应该没有这部分逻辑，你先访问 http://10.66.84.106:8080 看看是不是 config service 的页面？

我后续发现如果启动参数带auth环境，则所有接口全部报401，去除auth环境则没问题。
查看了一下应该是com.ctrip.framework.apollo.portal.spi.configuration.SpringSecurityAuthAutoConfiguration 类的问题？
但是我没有仔细看，具体什么原因。

**Comment by nobodyiam** [comment]
com.ctrip.framework.apollo.portal.spi.configuration.SpringSecurityAuthAutoConfiguration 这个是 portal 的配置类，在 config service 中是不会引用到的，除非你是自己打包的 all in one？
