### ISSUE TITLE
请问apollo v1.8.1如何使用nacos注册中心？

### ISSUE THREAD

**Issue by PostgreSQL1989** [ctripcorp/apollo#3690]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**
我看到v1.8.0开始支持nacos作为注册中心，请问如何配置？
我按照如下的文档进行配置，启动出现了报错。
https://github.com/ctripcorp/apollo/pull/3447

根据文档修改了打包参数
- 2.2.1.2.7 启用外部nacos服务注册中心替换内置eureka
`mvn clean package -Pgithub,nacos-discovery -DskipTests -pl apollo-configservice,apollo-adminservice -am -Dapollo_profile=github,nacos-discovery -Dspring_datasource_url=$apollo_config_db_url -Dspring_datasource_username=$apollo_config_db_username -Dspring_datasource_password=$apollo_config_db_password`

**期望**

目前apollo不支持zookeeper集群作为注册中心，想使用nacos作为注册中心使用，最终实现apollo服务高可用，避免单点故障。

**截图**

![image](https://user-images.githubusercontent.com/6407688/118628891-9e946180-b7ff-11eb-8a3c-df3bcd22833e.png)
![image](https://user-images.githubusercontent.com/6407688/118630408-157e2a00-b801-11eb-8700-eb13a6e54adb.png)

### 额外的细节和日志

- 版本：apollo v1.8.1, nacos v1.4.2(集群模式)
- 错误日志：

2021-05-18 17:31:06.310 ERROR 7614 --- [Apollo-AccessKeyServiceWithCache-1] c.c.f.a.c.s.AccessKeyServiceWithCache    : Load new/updated app access keys failed

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'entityManagerFactory': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-5.3.3.jar!/:5.3.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar!/:5.3.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.3.jar!/:5.3.3]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory$1.orderedStream(DefaultListableBeanFactory.java:481) ~[spring-beans-5.3.3.jar!/:5.3.3]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:167) ~[spring-tx-5.3.3.jar!/:5.3.3]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:149) ~[spring-tx-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145) ~[spring-data-jpa-2.4.3.jar!/:2.4.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at com.sun.proxy.$Proxy136.findFirst500ByDataChangeLastModifiedTimeGreaterThanOrderByDataChangeLastModifiedTimeAsc(Unknown Source) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at com.ctrip.framework.apollo.common.aop.RepositoryAspect.invokeWithCatTransaction(RepositoryAspect.java:27) ~[apollo-common-1.8.1.jar!/:1.8.1]
        at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.3.jar!/:5.3.3]
        at com.sun.proxy.$Proxy136.findFirst500ByDataChangeLastModifiedTimeGreaterThanOrderByDataChangeLastModifiedTimeAsc(Unknown Source) ~[na:na]
        at com.ctrip.framework.apollo.configservice.service.AccessKeyServiceWithCache.loadNewAndUpdatedAccessKeys(AccessKeyServiceWithCache.java:129) ~[classes!/:1.8.1]
        at com.ctrip.framework.apollo.configservice.service.AccessKeyServiceWithCache.scanNewAndUpdatedAccessKeys(AccessKeyServiceWithCache.java:100) ~[classes!/:1.8.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_102]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
2021-05-18 17:31:06.323  INFO 7614 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2021-05-18 17:31:06.324  INFO 7614 --- [main] AnnotationNacosInjectedBeanPostProcessor : com.alibaba.nacos.spring.factory.DelegatingNamingService@79eade07 was destroying!
2021-05-18 17:31:06.324  INFO 7614 --- [main] AnnotationNacosInjectedBeanPostProcessor : class com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor was destroying!
2021-05-18 17:31:06.332  INFO 7614 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-05-18 17:31:06.342  WARN 7614 --- [main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [Apollo-ConfigRefresher-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2021-05-18 17:31:06.342  WARN 7614 --- [main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [Apollo-AccessKeyServiceWithCache-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2021-05-18 17:31:06.374  INFO 7614 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-18 17:31:06.426 ERROR 7614 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

server error: invalid param. failed to req API:/api//nacos/v1/ns/instance after all servers([nacos.xinc818.com:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue May 18 17:31:06 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 172.16.250.138</div></body></html>

Action:

please check server status

- 配置：
- apollo-adminservice
cat apollo-adminservice-1.8.1/config/application-github.properties
`# DataSource`
`spring.datasource.url = jdbc:mysql://xxxx.mysql.rds.aliyuncs.com:3331/ApolloConfigDB_prod?characterEncoding=utf8`
`spring.datasource.username = apollo_online`
`spring.datasource.password = xxxx`
`#nacos discovery`
`nacos.discovery.server-addr=nacos.xxxx.com:8848`

grep 'Dapollo_profile' apollo-adminservice-1.8.1/scripts/startup.sh
`export JAVA_OPTS="$JAVA_OPTS -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dapollo_profile=github,auth,nacosDiscovery"`

- apollo-configservice
cat apollo-configservice/config/application-github.properties
`# DataSource`
`spring.datasource.url = jdbc:mysql://xxxx.mysql.rds.aliyuncs.com:3331/ApolloConfigDB_prod?characterEncoding=utf8`
`spring.datasource.username = apollo_online`
`spring.datasource.password = xxxx`
`#nacos discovery`
`nacos.discovery.server-addr=nacos.xxxx.com:8848`

grep 'Dapollo_profile' apollo-configservice/scripts/startup.sh
`export JAVA_OPTS="$JAVA_OPTS -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dapollo_profile=github,auth,nacosDiscovery"`

- 平台和操作系统：CentOS 7

**Comment by nobodyiam** [comment]
看下这个报错吧，是 nacos client 打出来的，应该是访问服务端报错了
![image](https://user-images.githubusercontent.com/837658/118738110-dc819c00-b878-11eb-9f65-a4bf0e0e32f8.png)

**Comment by PostgreSQL1989** [comment]
> 看下这个报错吧，是 nacos client 打出来的，应该是访问服务端报错了
> ![image](https://user-images.githubusercontent.com/837658/118738110-dc819c00-b878-11eb-9f65-a4bf0e0e32f8.png)

感谢你的回复。
我这边试过server，用curl访问是可以注册发布和获取的。
请问一下，我配置application-github.properties里面的nacos，只要有这一段就行了吗？是否需要配置账号密码？如果需要账号密码，改如何配置？
nacos.discovery.server-addr=nacos.xxxx.com:8848

**Comment by klboke** [comment]
如果 nacos-server 开启了认证，可以参考这个 pr 里的方式添加配置：https://github.com/ctripcorp/apollo/pull/3695/files

**Comment by PostgreSQL1989** [comment]
> 如果 nacos-server 开启了认证，可以参考这个 pr 里的方式添加配置：https://github.com/ctripcorp/apollo/pull/3695/files

感谢您的回复。
我把账号密码加上了，还是老样子。
请问您这边有可以用的配置吗？

#nacos discovery
nacos.discovery.server-addr=nacos.xxxx.com:8848
nacos.discovery.username=nacos
nacos.discovery.password=nacos

**Comment by PostgreSQL1989** [comment]
请问有人实现过吗？
感觉用不了nacos注册啊

**Comment by nobodyiam** [comment]
@klboke would you please help to take a look? though it looks more like a nacos client issue to me...

**Comment by klboke** [comment]
@PostgreSQL1989  从你的日志上看，apollo 里的 nacos 注册组件已经在正常工作了，看上去更像 nacos-server 响应了错误的内容，你那边可以尝试下切换个 nacos-server 的版本试试呢?

**Comment by PostgreSQL1989** [comment]
> @PostgreSQL1989 从你的日志上看，apollo 里的 nacos 注册组件已经在正常工作了，看上去更像 nacos-server 响应了错误的内容，你那边可以尝试下切换个 nacos-server 的版本试试呢?

感谢你的回复。
我用的是v1.4.2版本的nacos，请问你是用哪个版本的nacos实现的？
支持集群模式吗？
有nacos的配置样本吗？

#nacos discovery
nacos.discovery.server-addr=nacos.xxxx.com:8848
nacos.discovery.username=nacos
nacos.discovery.password=nacos

**Comment by klboke** [comment]
我是直接运行的 naocs 的代码，1.4.1 版本的，单机模式的。然后我看你运行的脚本和我们的文档好像有些出入，可以在确认下，我们的文档的内容如下：
##### 2.2.1.2.7 启用外部nacos服务注册中心替换内置eureka

1. 修改build.sh/build.bat，将config-service和admin-service的maven编译命令更改为
```shell
mvn clean package -Pgithub,nacos-discovery -DskipTests -pl apollo-configservice,apollo-adminservice -am -Dapollo_profile=github,nacos-discovery -Dspring_datasource_url=$apollo_config_db_url -Dspring_datasource_username=$apollo_config_db_username -Dspring_datasource_password=$apollo_config_db_password
```

2. 分别修改apollo-configservice和apollo-adminservice安装包中config目录下的application-github.properties，配置nacos服务器地址
```properties
nacos.discovery.server-addr=127.0.0.1:8848
# 更多 nacos 配置
nacos.discovery.access-key=
nacos.discovery.username=
nacos.discovery.password=
nacos.discovery.secret-key=
nacos.discovery.namespace=
nacos.discovery.context-path=
```

**Comment by PostgreSQL1989** [comment]
> 我是直接运行的 naocs 的代码，1.4.1 版本的，单机模式的。然后我看你运行的脚本和我们的文档好像有些出入，可以在确认下，我们的文档的内容如下：
> 
> ##### 2.2.1.2.7 启用外部nacos服务注册中心替换内置eureka
> 1. 修改build.sh/build.bat，将config-service和admin-service的maven编译命令更改为
> 
> ```shell
> mvn clean package -Pgithub,nacos-discovery -DskipTests -pl apollo-configservice,apollo-adminservice -am -Dapollo_profile=github,nacos-discovery -Dspring_datasource_url=$apollo_config_db_url -Dspring_datasource_username=$apollo_config_db_username -Dspring_datasource_password=$apollo_config_db_password
> ```
> 
> 1. 分别修改apollo-configservice和apollo-adminservice安装包中config目录下的application-github.properties，配置nacos服务器地址
> 
> ```ini
> nacos.discovery.server-addr=127.0.0.1:8848
> # 更多 nacos 配置
> nacos.discovery.access-key=
> nacos.discovery.username=
> nacos.discovery.password=
> nacos.discovery.secret-key=
> nacos.discovery.namespace=
> nacos.discovery.context-path=
> ```

感谢您的回复。
我的打包参数是没有错的，后来试了一下，单机模式是没问题的。
此外，请问nacos.discovery.namespace生效吗？我这边新建了namespace，改了这个参数，在nacos找不到相应的服务名。
如果用留空，可以在缺省的public里面找到响应的服务名。
再次感谢两位的热心回复。

**Comment by klboke** [comment]
你的问题好了么？`nacos.discovery.namespace `是生效的，这个是 [nacos-discovery-spring-boot-autoconfigure]( https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-config-spring-boot-autoconfigure/src/main/java/com/alibaba/boot/nacos/config/properties/NacosConfigProperties.java ) 提供的

**Comment by PostgreSQL1989** [comment]
> 你的问题好了么？`nacos.discovery.namespace `是生效的，这个是 [nacos-discovery-spring-boot-autoconfigure](https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-config-spring-boot-autoconfigure/src/main/java/com/alibaba/boot/nacos/config/properties/NacosConfigProperties.java) 提供的

感谢您的答复，我这边换个姿势试试，目前已经可以支持nacos了
