### ISSUE TITLE
Module Apollo Core test FAILURE when use java 11

### ISSUE THREAD

**Issue by Anilople** [ctripcorp/apollo#3746]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

Module Apollo Core test FAILURE when use java 11

```java
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in com.ctrip.framework.apollo.core.utils.DeferredLoggerTest
initializationError(com.ctrip.framework.apollo.core.utils.DeferredLoggerTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.ctrip.framework.test.tools.AloneClassLoader.<init>(AloneClassLoader.java:30)
	at com.ctrip.framework.test.tools.AloneRunner.<init>(AloneRunner.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**To Reproduce**
1. Use java 11
2. `mvn clean test`

**Expected behavior**

Test should pass.

### Additional Details & Logs

- Version: 1.9.0-SNAPSHOT
- Error logs 
[maven.test.log](https://github.com/ctripcorp/apollo/files/6602347/maven.test.log)
- surefire-reports 
[com.ctrip.framework.apollo.core.utils.DeferredLoggerTest.txt](https://github.com/ctripcorp/apollo/files/6602356/com.ctrip.framework.apollo.core.utils.DeferredLoggerTest.txt)
full [surefire-reports.zip](https://github.com/ctripcorp/apollo/files/6602361/surefire-reports.zip)
- Configuration 
- Platform and Operating System Win10 Git Bash
- result of `java -version`
```bash
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by nobodyiam** [comment]
emmm... to avoid such issues in the future, maybe we could add more jdk test cases in the github actions?

**Comment by Anilople** [comment]
> emmm... to avoid such issues in the future, maybe we could add more jdk test cases in the github actions?

Good idea
