### ISSUE TITLE
delete item操作返回400 item not exist

### ISSUE THREAD

**Issue by Tian90coder** [ctripcorp/apollo#3834]
![image](https://user-images.githubusercontent.com/56345542/126188884-6efbb18f-a18c-43c2-8609-b45b19969d13.png)

这个问题在我本地部署后100%复现，当我尝试在portal上删除item时，第三段代码根据id查询item不存在后会抛出“item not exist”。但是官网demo中的删除可以正常返回，这是什么原因？
~~~java
  // aop before 对namespace加锁
  @Before("@annotation(PreAcquireNamespaceLock) && args(itemId, operator, ..)")
  public void requireLockAdvice(long itemId, String operator) {
    Item item = itemService.findOne(itemId);
    if (item == null){
      throw new BadRequestException("item not exist.");
    }
    acquireLock(item.getNamespaceId(), operator);
  }
  
  // 删除item 审计 提交更改
  @PreAcquireNamespaceLock
  @DeleteMapping("/items/{itemId}")
  public void delete(@PathVariable("itemId") long itemId, @RequestParam String operator) {
    Item entity = itemService.findOne(itemId);
    if (entity == null) {
      throw new NotFoundException("item not found for itemId " + itemId);
    }
    itemService.delete(entity.getId(), operator);

    Namespace namespace = namespaceService.findOne(entity.getNamespaceId());

    Commit commit = new Commit();
    commit.setAppId(namespace.getAppId());
    commit.setClusterName(namespace.getClusterName());
    commit.setNamespaceName(namespace.getNamespaceName());
    commit.setChangeSets(new ConfigChangeContentBuilder().deleteItem(entity).build());
    commit.setDataChangeCreatedBy(operator);
    commit.setDataChangeLastModifiedBy(operator);
    commitService.save(commit);
  }

  // aop after 查询出item 和 namespace 释放锁
  @After("@annotation(PreAcquireNamespaceLock) && args(itemId, operator, ..)")
  public void requireLockAdvice(long itemId, String operator) {
    Item item = itemService.findOne(itemId);
    if (item == null) {
      throw new BadRequestException("item not exist.");
    }
    tryUnlock(namespaceService.findOne(item.getNamespaceId()));
  }
~~~

**Comment by Tian90coder** [comment]
这是堆栈
~~~java
com.ctrip.framework.apollo.common.exception.BadRequestException: item not exist.
    at com.ctrip.framework.apollo.adminservice.aop.NamespaceUnlockAspect.requireLockAdvice(NamespaceUnlockAspect.java:88)
    ...
    at com.ctrip.framework.apollo.adminservice.filter.AdminServiceAuthenticationFilter.doFilter(AdminServiceAuthenticationFilter.java:56)
    ...
~~~

**Comment by Tian90coder** [comment]
修改After为AfterReturning后解决问题
~~~java
  @PreAcquireNamespaceLock
  @DeleteMapping("/items/{itemId}")
  public Long delete(@PathVariable("itemId") long itemId, @RequestParam String operator) {
    Item entity = itemService.findOne(itemId);
    if (entity == null) {
      throw new NotFoundException("item not found for itemId " + itemId);
    }
    itemService.delete(entity.getId(), operator);

    Namespace namespace = namespaceService.findOne(entity.getNamespaceId());

    Commit commit = new Commit();
    commit.setAppId(namespace.getAppId());
    commit.setClusterName(namespace.getClusterName());
    commit.setNamespaceName(namespace.getNamespaceName());
    commit.setChangeSets(new ConfigChangeContentBuilder().deleteItem(entity).build());
    commit.setDataChangeCreatedBy(operator);
    commit.setDataChangeLastModifiedBy(operator);
    commitService.save(commit);

    return entity.getNamespaceId();
  }

  //delete item
  @AfterReturning(value = "@annotation(PreAcquireNamespaceLock) && args(itemId, operator, ..)", returning="namespaceId")
  public void requireLockAdvice(long itemId, String operator, Object namespaceId) {
    tryUnlock(namespaceService.findOne((Long) namespaceId));
  }
~~~

**Comment by Tian90coder** [comment]
通过以下配置可以从根本上解决：
~~~properties
spring.jpa.open-in-view=true
~~~

**Comment by nobodyiam** [comment]
你在本地部署的时候有啥特殊步骤或设置吗？

**Comment by krin-wang** [comment]
> 修改After为AfterReturning后解决问题

@Tian90coder @nobodyiam 

在delete里面已经 `itemService.delete(entity.getId(), operator);`.
`requireLockAdvice`里面 `Item item = itemService.findOne(itemId);` 就可能返回为空或者从cache里面读到(取决于spring.jp.open-in-view是否打开?).   这里获取 item的目的是为了得到 namespaceId，而不是真的需要Assert item是否为空. 

所以我觉得应该改为`AfterReturning`更好. 

`spring.jpa.open-in-view`最好还是不用设置为`true`.
https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

**Comment by nobodyiam** [comment]
`spring.jpa.open-in-view` 目前默认是启用的，所以这个 `400 item not exist` 的问题默认应该是没有的，不过确实是一个可以考虑优化的点，要测试一下还有哪些地方是依赖了这个特性。
