### ISSUE TITLE
在k8s中部署， Env health check failed

### ISSUE THREAD

**Issue by uania** [ctripcorp/apollo#3862]
下面是异常信息，10.244.5.52 可以在portal容器中ping通，我只配置了dev环境。

`2021-07-30 20:38:33.150  INFO 1 --- [erviceLocator-1] c.c.f.a.p.e.PortalMetaDomainService      : Located meta server address [http://10.244.5.52:8080] for env [DEV]
2021-07-30 20:38:33.344  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-07-30 20:38:33.396 ERROR 1 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://10.244.5.52:8080
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.244.5.52:8080
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:212)
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:116)
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:82)
        at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:27)
        at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:132)
        at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:108)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-07-30 20:38:33.398 ERROR 1 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed for 1 times which less than down threshold. down threshold:2, env: DEV, meta server address: http://10.244.5.52:8080
2021-07-30 20:38:33.936  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@338270ea, org.springframework.security.web.context.SecurityContextPersistenceFilter@1818d00b, org.springframework.security.web.header.HeaderWriterFilter@6144e499, org.springframework.security.web.authentication.logout.LogoutFilter@568ef502, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@663622b1, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@56a9a7b5, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@787a0fd6, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@18b45500, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7f64bd7, org.springframework.security.web.session.SessionManagementFilter@219edc05, org.springframework.security.web.access.ExceptionTranslationFilter@999cd18, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3c46e6f6]
2021-07-30 20:38:34.111  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-07-30 20:38:34.576  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2021-07-30 20:38:35.349  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path ''
2021-07-30 20:38:35.517  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8070 (http) with context path ''
2021-07-30 20:38:35.540  INFO 1 --- [           main] c.c.f.apollo.portal.PortalApplication    : Started PortalApplication in 19.806 seconds (JVM running for 21.748)`

**Comment by uania** [comment]
eureka上显示了admin和config两个服务

**Comment by uania** [comment]
重新读了一遍部署，修改了ApolloConfig.ServerConfig中eureka的地址后，可以正常启动portal

**Comment by qyk1995** [comment]
在k8s中部署在哪里添加eureka的地址？
