### ISSUE TITLE
集成后，不定时在tomcat里报错

### ISSUE THREAD

**Issue by myfreeway** [ctripcorp/apollo#644]
你好！集成apollo后，发现在tomcat里运行时，不定时的会报这个错误。现象是看到有tomcat进程，但是访问端口已经是404了。这是最后出现的日志。有什么建议吗？

> Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/APP1] appears to have started a thread named [Apollo-ConfigServiceLocator-1] but has failed to stop it. This is very likely to create a memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/APP1] appears to have started a thread named [Apollo-RemoteConfigRepository-1] but has failed to stop it. This is very likely to create a memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/APP1] appears to have started a thread named [Apollo-RemoteConfigLongPollService-1] but has failed to stop it. This is very likely to create a memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/APP1] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7beb687d]) and a value of type [org.codehaus.plexus.classworlds.realm.ClassRealm] (value [ClassRealm[plexus.core, parent: null]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/APP1] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@f712989]) and a value of type [java.lang.Class] (value [class oracle.sql.TypeDescriptorFactory]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/APP1] created a ThreadLocal with key of type [org.codehaus.plexus.component.builder.XBeanComponentBuilder$1] (value [org.codehaus.plexus.component.builder.XBeanComponentBuilder$1@4f8df237]) and a value of type [java.util.LinkedHashSet] (value [[]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/APP1] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@c61d616]) and a value of type [java.lang.Class] (value [class oracle.sql.AnyDataFactory]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 19, 2017 3:32:01 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/APP1] created a ThreadLocal with key of type [com.google.common.escape.Platform$1] (value [com.google.common.escape.Platform$1@2ce9ff67]) and a value of type [char[]] (value [[C@2a52a612]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Jun 19, 2017 3:36:00 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load com.ctrip.framework.apollo.Apollo.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1599)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$1.run(RemoteConfigRepository.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jun 19, 2017 3:36:28 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load com.ctrip.framework.apollo.Apollo.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1599)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$1.run(RemoteConfigRepository.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by myfreeway** [comment]
几个应用放到一个tomcat里运行的。这几个应用都集成Apollo了。

**Comment by nobodyiam** [comment]
这个是tomcat shutdown阶段的一个thread check，Apollo的线程都是daemon线程，所以没关系的。

至于那个报错是因为在shutdown阶段，线程执行的时候，一些class已经unload掉了，所以也是正常的。

**Comment by nobodyiam** [comment]
先关闭了。

**Comment by bazaCC** [comment]
请问你最后怎么解决的？我现在也遇到这个问题了

**Comment by xiongrt** [comment]
同上

**Comment by amadisme** [comment]
怎么解决了，我至今也没解决

**Comment by thinking-github** [comment]
早期版本java apollo client application shutdown，  apollo thread pool 没有关闭，  应该算的bug ， 新版本修复了， 升级新版java apollo client试试
