### ISSUE TITLE
configservice是否可以使用ngnix代理，应该怎么操作？

### ISSUE THREAD

**Issue by llxiao** [ctripcorp/apollo#657]
望解答，谢谢

**Comment by lepdou** [comment]
可以用ngnix代理。比如你在生产环境部署了两个config server（10.0.0.1和10.0.0.2），ngnix的域名是www.config.example.com

1. 第一步在configdb的serverconfig表 eureka.service.url 配置项配置 http://10.0.0.1:8080/eureka/,http://10.0.0.2:8080/eureka/ 

2. 修改build.sh脚本，pro_meta=http://www.config.example.com

这样就可以了

**Comment by llxiao** [comment]
多谢，解答

**Comment by llxiao** [comment]
修改后的get请求，除了/services/config 其他还是请求的本地ip，是什么原因造成的

**Comment by lepdou** [comment]
因为/services/config 这个endpoint是用来给client获取所有的config server的地址的。所以这个请求是可以走域名的。当client获取到config server地址列表之后，就会从中随机挑一个IP，直连。也就是说，后续获取配置和监听配置更新的长连接都是IP直连的方式。不是走域名，如果走域名的话，所有的长连接都直接连到nginx了。

**Comment by seven7ma** [comment]
@lepdou 我按您这么配的,portal端报错,是哪的问题呢,
错误信息:2018-04-25 15:59:27.385 ERROR 10164 --- [Apollo-EnvHealthChecker-1] c.c.f.a.p.c.RetryableRestTemplate        : 
Http request failed, uri: health, method: GET
java.lang.IllegalArgumentException: Not enough variable values available to expand '10.1.3.149'
	at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:327)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:230)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:326)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:47)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:163)
	at org.springframework.web.util.DefaultUriTemplateHandler.expand(DefaultUriTemplateHandler.java:101)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:556)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:190)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:95)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:47)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
2018-04-25 15:59:27.386 ERROR 10164 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : 
Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://10.1.3.149:8888
java.lang.IllegalArgumentException: Not enough variable values available to expand '10.1.3.149'
	at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:327)
	at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:230)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:326)
	at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:47)
	at org.springframework.web.util.UriComponents.expand(UriComponents.java:163)
	at org.springframework.web.util.DefaultUriTemplateHandler.expand(DefaultUriTemplateHandler.java:101)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:556)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:190)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:95)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:47)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
2018-04-25 15:59:27.386 ERROR 10164 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  :
 Env is down. env: DEV, failed times: 338, meta server address: http://10.1.3.149:8888

**Comment by seven7ma** [comment]
![image](https://user-images.githubusercontent.com/24469163/39233062-ddc203f6-48a1-11e8-8a1b-6069a17fcee8.png)

**Comment by seven7ma** [comment]
![image](https://user-images.githubusercontent.com/24469163/39233110-059028cc-48a2-11e8-9963-b23a77d149f1.png)

**Comment by nobodyiam** [comment]
@seven7ma 你访问 `http://10.1.3.149:8888/services/admin` 看看结果是什么

**Comment by seven7ma** [comment]
![image](https://user-images.githubusercontent.com/24469163/39283501-23312f12-4941-11e8-9f9e-e18643271298.png)

**Comment by seven7ma** [comment]
[{"appName":"APOLLO-ADMINSERVICE","instanceId":"bogon:apollo-adminservice:8090","homepageUrl":"http://${10.1.3.149}:${8888}"},{"appName":"APOLLO-ADMINSERVICE","instanceId":"LAPTOP-KT5RMFJL:apollo-adminservice:8090","homepageUrl":"http://${10.1.3.149}:${8888}"}]

**Comment by nobodyiam** [comment]
homepageUrl信息错了，IP和端口不应该有花括号的，你看下是不是配置的地方写错了。

应该是`http://10.1.3.149:8888`这样的

**Comment by seven7ma** [comment]
额, 太马虎了,多谢了大哥!
