### ISSUE TITLE
docker部署运行sample总是出现以下报错信息 Failed to create transaction for type: Apollo.ConfigService, name: pollNotification

### ISSUE THREAD

**Issue by jeanhao** [ctripcorp/apollo#685]
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-10 16:13:43,067 WARN  [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: pollNotification
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(RemoteConfigLongPollService.java:145) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.access$100(RemoteConfigLongPollService.java:48) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService$2.run(RemoteConfigLongPollService.java:118) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-10 16:13:43,067 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling from http://apollo-configservice:8080/notifications/v2?cluster=default&appId=apollo-spring-boot-sample&ip=192.168.67.208&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A1%7D%5D
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-10 16:14:14,070 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling response: 304, url: http://apollo-configservice:8080/notifications/v2?cluster=default&appId=apollo-spring-boot-sample&ip=192.168.67.208&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A1%7D%5D

**Comment by nobodyiam** [comment]
我们看了下代码，com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) 这个地方不应该出现NPE的。。。除非运行时跑到了ut的代码。。

你能看下实际运行的jar包里面的`com.ctrip.framework.apollo.tracer.spi.MessageProducerManager`文件内容是啥吗？

正常的应该是和这个[链接](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/resources/META-INF/services/com.ctrip.framework.apollo.tracer.spi.MessageProducerManager)内容一样的。

**Comment by jeanhao** [comment]
是和链接里一样的

**Comment by jeanhao** [comment]
下面是我添加了自己的配置信息后，更详细的报错信息，不知道有没帮助：
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-12 17:32:03,571 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: pollNotification
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(RemoteConfigLongPollService.java:145) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.access$1(RemoteConfigLongPollService.java:134) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService$2.run(RemoteConfigLongPollService.java:118) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-12 17:32:03,576 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling from http://apollo-configservice:8080/notifications/v2?cluster=default&appId=jeanheo_basic&ip=192.168.67.208&notifications=%5B%7B%22namespaceName%22%3A%22brainagi.database%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22brainagi.jgame%22%2C%22notificationId%22%3A-1%7D%5D
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-12 17:32:03,601 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling response: 200, url: http://apollo-configservice:8080/notifications/v2?cluster=default&appId=jeanheo_basic&ip=192.168.67.208&notifications=%5B%7B%22namespaceName%22%3A%22brainagi.database%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22brainagi.jgame%22%2C%22notificationId%22%3A-1%7D%5D
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-12 17:32:03,603 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: pollNotification
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.doLongPollingRefresh(RemoteConfigLongPollService.java:145) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService.access$1(RemoteConfigLongPollService.java:134) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigLongPollService$2.run(RemoteConfigLongPollService.java:118) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,603 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: syncRemoteConfig
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:112) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,604 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to log event for type: Apollo.Client.ConfigMeta, name: jeanheo_basic+default+brainagi.database
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.logEvent(Tracer.java:61) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:156) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:116) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigLongPollService-1]2017-08-12 17:32:03,604 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigLongPollService] Long polling from http://apollo-configservice:8080/notifications/v2?cluster=default&appId=jeanheo_basic&ip=192.168.67.208&notifications=%5B%7B%22namespaceName%22%3A%22brainagi.database%22%2C%22notificationId%22%3A11%7D%2C%7B%22namespaceName%22%3A%22brainagi.jgame%22%2C%22notificationId%22%3A9%7D%5D
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,604 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Loading config from http://apollo-configservice:8080/configs/jeanheo_basic/default/brainagi.database?ip=192.168.67.208&releaseKey=20170811234934-871324aa9adf4916
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,604 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: queryConfig
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:177) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:116) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,615 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Config server responds with 304 HTTP status code.
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,615 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to log event for type: Apollo.Client.Configs.brainagi.database, name: 20170811234934-871324aa9adf4916
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.logEvent(Tracer.java:61) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:126) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,615 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: syncRemoteConfig
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:112) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,615 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to log event for type: Apollo.Client.ConfigMeta, name: jeanheo_basic+default+brainagi.jgame
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.logEvent(Tracer.java:61) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:156) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:116) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,616 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Loading config from http://apollo-configservice:8080/configs/jeanheo_basic/default/brainagi.jgame?ip=192.168.67.208&releaseKey=20170811155822-0792b9d8219fefe1
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,616 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to create transaction for type: Apollo.ConfigService, name: queryConfig
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:177) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:116) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,619 DEBUG [com.ctrip.framework.apollo.internals.RemoteConfigRepository] Config server responds with 304 HTTP status code.
[apollo-client][Apollo-RemoteConfigRepository-1]2017-08-12 17:32:03,619 DEBUG [com.ctrip.framework.apollo.tracer.Tracer] Failed to log event for type: Apollo.Client.Configs.brainagi.jgame, name: 20170811155822-0792b9d8219fefe1
java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.Tracer.logEvent(Tracer.java:61) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:126) [classes/:?]
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22) [classes/:?]
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
