### ISSUE TITLE
引入com.dianying.cat.Cat抛出NullPointerException

### ISSUE THREAD

**Issue by shushanfx** [ctripcorp/apollo#768]
根据`CatMessageProducer`的定义，引入`com.dianping.cat.Cat`就可以记录所有的Transaction行为，但是在实际过程中，抛出NullPointerException，异常信息如下：
```
java.lang.IllegalStateException: java.lang.NullPointerException
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:81)
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.loadApolloConfig(RemoteConfigRepository.java:177)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.sync(RemoteConfigRepository.java:116)
	at com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:22)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository$2.run(RemoteConfigRepository.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79)
	... 12 more
[Apollo-RemoteConfigRepository-1] WARN com.ctrip.framework.apollo.tracer.Tracer - Failed to log event for type: Apollo.Client.Configs.application, name: 20170906193012-7481357d7b823b4f
```
Cat定义如下：
```java
package com.dianping.cat;

import com.ctrip.framework.apollo.tracer.internals.NullTransaction;
import com.ctrip.framework.apollo.tracer.spi.MessageProducer;
import com.ctrip.framework.apollo.tracer.spi.Transaction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Cat implements MessageProducer{
    private static final Logger logger = LoggerFactory.getLogger(Cat.class);

    public void logError(Throwable throwable){
        logger.error(throwable.getMessage(), throwable);
    }

    public void logError(String message, Throwable throwable){
        logger.error(message, throwable);
    }

    public void logEvent(String type, String message){
        logEvent(type, message, null, null);
    }

    public void logEvent(String type, String message, String status, String name){
        logger.info("Type: {}, Message: {}, Status: {}, Name: {}", type, message, status, name);
    }

    public Transaction newTransaction(String type, String message){
        return new NullTransaction();
    }
}
```
请看下该问题，谢谢：）

**Comment by nobodyiam** [comment]
看上去是 NEW_TRANSACTION_WITH_TYPE_AND_NAME 为NULL，你到 https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/internals/cat/CatMessageProducer.java#L30 打个断点看看？

另外，你这个CAT是自己写的？不是开源的那个实现？

**Comment by shushanfx** [comment]
Cat是参照CatMessagerProducer加载的方法自己写的。我本地打断点调试时，https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/internals/cat/CatMessageProducer.java#L79，这句抛出的异常，应该是invoke时第一个参数是null导致的。

**Comment by WJspring** [comment]
建议小心使用cat，我们生产上cat服务端莫名挂了以后，客户端监听心跳队列无限制递增，导致内存泄露，应用dump。

**Comment by qmwu2000** [comment]
CAT新版本对这个问题有过修复，建议更新下版本

发自我的 iPhone

**Comment by nobodyiam** [comment]
@shushanfx 那看来还是因为没有获取到newTransaction的方法，你到[CatMessageProducer.java的30行](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/apollo/tracer/internals/cat/CatMessageProducer.java#L30)加个断点看一下吧，是否是因为运行时load到的Cat class和你贴的不一样。

```java
NEW_TRANSACTION_WITH_TYPE_AND_NAME = CAT_CLASS.getMethod(
          CatNames.NEW_TRANSACTION_METHOD, String.class, String.class);
```

**Comment by nobodyiam** [comment]
暂时先关闭了，如有问题，可以提供更多信息，谢谢~
