### ISSUE TITLE
apollo启动问题

### ISSUE THREAD

**Issue by Baivin** [ctripcorp/apollo#821]
你好，我想请问一下，配置中心如何确保启动优先级，保证在获取它的值之前，把所有内容放入了spring容器？会不会出现${key}获取值时，配置中心还没注入值，导致获取值为空的情况？

**Comment by nobodyiam** [comment]
不会的，因为apollo是在postProcessBeanFactory注入配置的，早于bean创建阶段。有兴趣的话可以去google一下spring生命周期的说明。

**Comment by wuwen5** [comment]
```
java.lang.IllegalStateException: Service id not legal hostname (${marketing.ms.customer.serviceName})
	at org.springframework.util.Assert.state(Assert.java:70)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:238)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:181)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:167)
	at org.springframework.cloud.netflix.feign.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:92)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:359)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
```
的确是存在优先级问题，在使用feign的时候启动加载不到配置项，apollo的配置在这之后加载到spring容器的。 spring cloud config没有这样的问题。

**Comment by nobodyiam** [comment]
@wuwen5 Pull Request #923 针对spring boot环境做了新特性，可以支持在启动阶段就把Apollo的配置注入进去，等后面合并了就可以使用了
