### ISSUE TITLE
进项目一直提示系统出错，请重试或联系系统负责人

### ISSUE THREAD

**Issue by sangjie** [ctripcorp/apollo#874]
有可能是什么 原因呢，该看哪里的日志

**Comment by lepdou** [comment]
看portal的日志，日志路径在startup.sh启动脚本里有

**Comment by sangjie** [comment]
2017-12-08 06:54:08.127 ERROR 2989 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address:  http://*:7160

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://*:7160
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:172)

**Comment by sangjie** [comment]
和我把程序部署到本地linux虚拟机上有关系吗

**Comment by nobodyiam** [comment]
No available admin server

你打开http://*:7160看看admin service有没有注册上来，或者访问http://*:7160/services/admin看返回对不对，话说为啥要把config service的端口改成7160？这样你必须还得同时改ApolloConfigDB.ServerConfig中的eureka.service.url配置的端口

**Comment by dreamoftch** [comment]
按照Quick Start的步骤，最后出现同样的问题

**Comment by nobodyiam** [comment]
@dreamoftch quick start刚启动时由于Eureka更新较慢，在短时间内可能会出现这个错误提示，稍微过一会儿就会正常了

**Comment by chenbin9333** [comment]
很可能是服务没启动好，我这边试了是端口占用的问题，如下：

admin service启动在8090端口。请确认这两个端口是否被其它应用程序占用。
比如，ShadowSocks默认会占用8090端口。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by Marviszhao** [comment]
```
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down
```
![image](https://user-images.githubusercontent.com/6290252/44135252-ed94d1cc-a09a-11e8-9baf-1bdfc579b305.png)

**Comment by Marviszhao** [comment]
@nobodyiam 这个homepageUrl  "http://169.254.176.207:8090/" 不知道是在哪里注册的，麻烦看下是不是那个地方的缓存，谢谢！
![image](https://user-images.githubusercontent.com/6290252/44135815-33cbe494-a09d-11e8-85e8-54cd1b5c6a58.png)

**Comment by nobodyiam** [comment]
这个是admin server自动注册上来的，eureka默认会有90秒的缓存，如果你这个一直存在的话，可能就不是缓存的问题了。可以看看是不是起了多个admin service

**Comment by wallacefw1987** [comment]
我也遇到这个问题，按照wiki教程配置apollo-portal，在配置resources/apollo-env.properties文件如下：
local.meta=http://10.168.2.20:8020
dev.meta=http://10.168.2.20:8020
fat.meta=http://10.168.2.20:8020
uat.meta=http://10.168.2.20:8020
控制台依然出现这个 问题：
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.168.2.20:8020
而且 http://10.168.2.20:8020是可以登录eureka服务器的

**Comment by nobodyiam** [comment]
当前meta server配置的是指向config service地址，你打开 `http://10.168.2.20:8020/services/admin`看看？

**Comment by zeuskingzb** [comment]
admin service启动在8090端口。请确认这两个端口是否被其它应用程序占用。
比如，**ShadowSocks**默认会占用8090端口。



`lsof -i:8090
COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Shadowsoc 11084 snow.zhang    4u  IPv4 0x6e04e88dbd3eb251      0t0  TCP *:8090 (LISTEN)`

**Comment by SnailJogging** [comment]
修改configservice、adminservice、portalservice端口后，好需要修改什么

**Comment by zerols** [comment]
> 修改configservice，adminservice，portalservice端口后，好需要修改什么？？？

编译过后 修改三个对应的端口 还需要改什么啊

**Comment by zhaoyahui** [comment]
com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://fill-in-dev-meta-server:8080
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:175)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:93)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:59)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:126)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
