### ISSUE TITLE
请问，启动的时候报java.net.ConnectException: Connection refused 是什么原因呢

### ISSUE THREAD

**Issue by sangjie** [ctripcorp/apollo#875]
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)

**Comment by lepdou** [comment]
如果只是启动过程中报的，那没有关系。只要不是一直在报就可以了。因为config service既是服务注册中心又是服务的client，所以一开始启动的时候尝试注册就会报错，因为服务都还没有起起来。

**Comment by sangjie** [comment]
谢谢，Connection refused (Connection refused)一直都在报

**Comment by nobodyiam** [comment]
一直在报的话，估计ApolloConfigDB.ServerConfig的eureka.service.url配置不对？

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
