### ISSUE TITLE
补缺失环境时失败

### ISSUE THREAD

**Issue by tcrct** [ctripcorp/apollo#980]
在补缺环境时，
前台提示弹窗
load env :DEV cluster error.404 Not Found

======================================

后台日志：

2018-03-05 17:49:49.801 ERROR 10119 --- [http-nio-6070-exec-6] c.c.f.a.p.c.RetryableRestTemplate        : Http request failed, uri: apps/2012110500/clusters, method: GET

org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:264)
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:190)
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:95)
        at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
        at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$ClusterAPI.findClustersByApp(AdminServiceAPI.java:179)
        at com.ctrip.framework.apollo.portal.service.ClusterService.findClusters(ClusterService.java:25)
        at com.ctrip.framework.apollo.portal.service.AppService.createEnvNavNode(AppService.java:138)
        at com.ctrip.framework.apollo.portal.service.AppService$$FastClassBySpringCGLIB$$99928c13.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
        at com.ctrip.framework.apollo.portal.service.AppService$$EnhancerBySpringCGLIB$$faa6eba2.createEnvNavNode(<generated>)
        at com.ctrip.framework.apollo.portal.controller.AppController.nav(AppController.java:113)
        at com.ctrip.framework.apollo.portal.controller.AppController$$FastClassBySpringCGLIB$$dc9562f1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651)
        at com.ctrip.framework.apollo.portal.controller.AppController$$EnhancerBySpringCGLIB$$6e4a91ef.nav(<generated>)
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

如何处理？

**Comment by nobodyiam** [comment]
缺少数据的环境是新增的还是本来就有的？

**Comment by nobodyiam** [comment]
@tcrct 如果是新增的环境，建议参考[2.1.2.1 从别的环境导入ApolloConfigDB的项目数据](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#2121-%E4%BB%8E%E5%88%AB%E7%9A%84%E7%8E%AF%E5%A2%83%E5%AF%BC%E5%85%A5apolloconfigdb%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%95%B0%E6%8D%AE)对新的环境做初始化。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。

**Comment by tianqing108** [comment]
怎么解决的
